### ISSUE TITLE
HMR (with Vite) randomly skip updates and stop working

### ISSUE THREAD

**Issue by mkhennoussi** [nuxt/framework#1036]
### Environment

Nuxt CLI v3.0.0-27236898.4a34c2a                                      
RootDir: G:\PROJECTS\Testing\NUXT\nuxt3-app
Nuxt project info:
```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.8.0`
- Nuxt Version:     `3-3.0.0-27236898.4a34c2a`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Describe the bug

HMR with Vite randomly skip updates, I mean some (random I guess) updates on the code don't show up on the browser.

### Reproduction

Just use the basic generated app from the CLI and add/remove some code in the template part of `app.vue`.
Repeat that until you notice that some updates on the code don't show up on the browser.
It is more noticeable if you work fast with `tailwindcss/windicss`.

**Comment by productdevbook** [comment]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27255771.f78ec93`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.0`
------------------------------


### Describe the bug


https://user-images.githubusercontent.com/38668796/139138186-7cd201f5-ab03-4a38-93bc-46ebe6cdc2d8.mp4



### Reproduction

https://github.com/productdevbook/nuxt3-app

### Additional context

This seems to me to be in vite.  because when I translate css, it fixes the project. There seems to be a problem with compiling Sass. but we're not entirely sure

### Logs

```shell
✔ Vite server built in 111ms
(node:15424) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by productdevbook** [comment]
Component used new problem

<img width="1434" alt="CleanShot 2021-11-03 at 06 37 50@2x" src="https://user-images.githubusercontent.com/38668796/140006946-ebdc291a-bad9-4661-ae27-10cf1c7015fc.png">

**Comment by productdevbook** [comment]
css some problem
<img width="770" alt="CleanShot 2021-11-13 at 12 24 06@2x" src="https://user-images.githubusercontent.com/38668796/141613598-361611e8-2d8c-4415-a0fe-401017ae3255.png">

**Comment by void0err** [comment]
+1 I face this problem as well.

**Comment by mortbauer** [comment]
Just started with the nuxt3-app template and have the same issue

**Comment by ryanaltvater** [comment]
I'm not sure if this is related/helpful or not, but I'm experiencing similar issues with components specifically. When updating a pre-existing component, HMR doesn't refresh. It feels as if the `components/` folder isn't being watched for changes. When adding a new component and calling it on a page, HMR breaks. If I make changes elsewhere on the page (not to the component) to test if HMR still works for regular changes, HMR is broken.  So, in order to get the component to render on the page and HMR to start working, I have to restart the server. HMR then watches for regular page changes until components somehow break things again.

**Comment by moh1434** [comment]
For me HMR dose not work in fresh `npx nuxi init nuxt3-app` project.

```
<template>
  <div>
    {{ testVar }}
  </div>
</template>

<script setup>
const testVar = ref("some text");
</script>
```

If i remove `const testVar` line, i will see `Vite server built in 84ms` but nothing will change in the browser(also vue dev-tools will still show `testVar:"some text"` even when click force refresh icon).

**Comment by huuhait** [comment]
it's still not fixed?

**Comment by Atinux** [comment]
@antfu can you take a look at it after your holidays?

**Comment by danielroe** [comment]
see also https://github.com/nuxt/framework/issues/3006

**Comment by WSlim4** [comment]
I'm facing this problem as well

**Comment by WSlim4** [comment]
I'm having this problem too, using nuxt3 default template

**Comment by OlegIvaniv** [comment]
For me also HMR is broken after starting a new project via `nuxi init`.

**Comment by antfu** [comment]
I am investigating this. 

I can reliably reproduce this behavior in https://github.com/nuxt/modules by editing the `TheHeader.vue` file. Client console emits this error:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/11247099/153346742-47b82774-91e2-4343-adbe-48c2efd85452.png">

From what I can see the error is caused by Vue failing to retrieve the DOM `el` on HMR. Which I suspect would be caused by some hydration mismatch. However, I still can't locate the root cause yet.

For everyone in this thread, I would be appreciated to receive a **minimal reproduction** repo or Stackblitz as I can't reproduce it with the starter template myself. Thanks ahead!

**Comment by productdevbook** [comment]
@antfu https://github.com/productdevbook/nuxt3-app

**Comment by productdevbook** [comment]
Hi @antfu,
 
https://github.com/productdevbook/nuxt3-app 

upgrade new vue 3.2.31 and all dependencies. (yarn.lock delete and re-install).

Hot reload fixed but, text, background color change but dont hot reload change.

**Comment by Of3lia** [comment]
If helps for something, I was having this same problem on a Vue 3 Vite + typescript project, and fixed it by undoing the last thing I did that was exporting something from main.js and importing it on other places of my project, so I moved it to a pinia store and im using it from the state now hot reload is working fine

**Comment by kschluter** [comment]
Similar issue as Of3lia, renamed a component and HMR broke. Deleting node modules and reinstalling fixed.

**Comment by nopeless** [comment]
Just in case some developer stumbles upon this I emptied cache and hard reloaded it works again

**Comment by geilix10** [comment]
Comments above seemed not to work for me. 
What helped was to deactivate ssr in the Nuxt Config. 
```
ssr: false
```

Worked fine after that. (Develop purpose only)

**Comment by sebpalluel** [comment]
> Just in case some developer stumbles upon this I emptied cache and hard reloaded it works again

That fixed it for me (in chrome's dev tool, Application/Storage => Clear site data), disabling ssr had no effect. If you are using docker, don't forget to open the port `24678` that is used by default for vite HMR.

**Comment by andrecampll** [comment]
> Comments above seemed not to work for me. What helped was to deactivate ssr in the Nuxt Config.
> 
> ```
> ssr: false
> ```
> 
> Worked fine after that. (Develop purpose only)

Thanks! It worked fine here :)

**Comment by antfu** [comment]
@scratchmex Please create a new issue with a minimal reproduction for us to track, thanks.

**Comment by 0fatihyildiz** [comment]
I created a new nuxt 3 project and I had this problem, but only the files in the pages directory were not hot reloaded. For this I tried replacing the `'Pages'` filename with `'pages'` and it worked.
