### ISSUE TITLE
Building to .output is placing public files in 2 separate locations

### ISSUE THREAD

**Issue by ryanaltvater** [nuxt/framework#1192]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.10.0`
- Nuxt Version:     `3-3.0.0-27238235.a1bcc53`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Describe the bug

`npm run build` is placing `public` files in 2 different locations within the `.output` folder. One location is `public` root, and the other location is the `_nuxt` root.

![Screen Shot 2021-10-18 at 1 43 50 PM](https://user-images.githubusercontent.com/1336787/137781115-aa9a465d-a95b-463d-8fb4-980688e1ee76.png)

### Reproduction

Add anything to the `public` folder, run the command `npm run build`, then open the `.output/public` folder to see the duplication.

**Comment by rmenai** [comment]
The main bug was fixed with the 2nd release candidate but I just noticed that there is now a smaller bug.

Now if we add an `images` directory to the public directory I noticed that it will appear two times, firstly in the root of the build as expected but also **empty** in the `_nuxt` directory.
![image](https://user-images.githubusercontent.com/59766203/167306537-105deeb9-f633-4bcd-a672-81ac172055d1.png)
![image](https://user-images.githubusercontent.com/59766203/167306518-a475ab95-67ca-40f6-a34c-54c07bc4133b.png)
