### ISSUE TITLE
nuxt bridge __webpack_hmr/client 404 Not Found

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/framework#1325]
### Environment

Nuxt project info:                                                                                                                           18:38:21

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.11.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

when project is running devtools complains about __webpack_hmr/client 404 Not Found

### Reproduction

create a new nuxt2 app with npx create-nuxt-app
follow the docs to convert  it to bridge.
run npm run dev open browser on hosted server, then open devtools.

### Additional context

non

### Logs

```shell
Firefox can’t establish a connection to the server at http://127.0.0.1:3000/__webpack_hmr/client.
```

**Comment by cpt-n3mo** [comment]
Oh i see, this is on me, i did not notice that i was not using a default template for my nuxt.config.js
the trouble comes in when.

```
router: {
   base: '/something'
}
```
is added to the nuxt.config.js

it wants to connect to `/something/__webpack_hmr/client`
but the actual working url is `/__webpack_hmr/client`
and so this causes a 404 not found.

`_nuxt/**/*.js` files are still found and is redirected properly.. 

so it seems  `__webpack_hmr/client` is not redirected to the new base url..

kind regards.

**Comment by Schetnan** [comment]
The same problem occurs on nuxt3.  To produce on nuxt3, you have to set vite: false in the nuxt.config.ts.  And as above set a router.base in nuxt.config.ts. The hmr files can't be found.

If you don't set vite: false, the opposite problem occurs.  The hmr files are always attempted to be loaded at /_nuxt/...
When running behind a proxy, we get 404's, because the contextRoot ( router.base ) is not honored.

When not using vite, at least the URL honors the route.base ( which is good ).  It looks like /base/_nuxt/...   which is needed to run the app behind a proxy.  However, the hmr requests throw 404s.

**Comment by danielroe** [comment]
I cannot now replicate this, with the merge of #2655 

```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    vite: false
  },
  app: {
    basePath: '/foo'
  }
})
```

Let me know if you continue to experience it and I'll reopen it.
