### ISSUE TITLE
Mock vue-demi

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1737]
Some libraries might use `vue-demi` and we are already mocking vue3 interface for bridge. Mocking `vue-demi` by name, can prevent any potential issues with `@vuejs/composition-api` compatibility.

**Comment by antfu** [comment]
One note: due to the reactivity caveats, `@vue/composition-api` has additional APIs `set` and `del` for setting manipulating the new props of an object. To align that, `vue-demi` mock those API in Vue 3, where some lib might rely on (VueUse for example). Meanwhile, `vue-demi` also exposes `isVue2` and `isVue3`. If we do, we might also want to do the same for our mock.

**Comment by pi0** [comment]
Thanks for the note @antfu. I'm wondering was there any specific reason `set` and `del` wasn't exposed from `@vue/composition-api` (and does it worth to attempt a PR)

**Comment by antfu** [comment]
`set` and `del` are from `@vue/composition-api` but **not in Vue 3** - since it's no need in Vue 3. `vue-demi` mock those API for Vue 3 so libraries can use them across both version.
