### ISSUE TITLE
There is no typescript runtime errors

### ISSUE THREAD

**Issue by grindpride** [nuxt/framework#1817]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27274229.29599f0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `dev`, `vite`, `build`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

I write incorrect code in setup() and only see highlights in my IDE, `nuxi dev` runs without errors

### Reproduction

https://codesandbox.io/s/4x828?file=/app.vue

**Comment by pi0** [comment]
Hi @grindpride. It is expected since for performance reasons, instead of typescript/tsc (that does type checking), Nuxt uses [esbuild](https://github.com/evanw/esbuild) (for vite, webpack and nitro) and ESBuild simply strips the type declarations to compile. (Read more: https://esbuild.github.io/content-types/#no-type-system). 

I have moved docs to #1819 and feature request to #1818

In the meantime, you can add `typescript` as a devDependency and use `tsc --noEmit` to check the types
