### ISSUE TITLE
Vuetify combined with Nuxt3

### ISSUE THREAD

**Issue by best-lucky1030** [nuxt/framework#1951]
### Environment

Windows 10
VS Code
Node:  v14.15.4
Nuxt 3
Vuetify 3.0 alpha

### Reproduction

https://github.com/dev-tom-0108/bug_tracker.git

### Describe the bug

When I tried to use v-data-table in Vuetify, I got the error.
I followed to use vuetify in nuxt at document, but it didn't work for me.

**Comment by danielroe** [comment]
I can't see what the issue is from looking at that repository. You don't seem to be using `<v-data-table>` or `vuetify` anywhere. Feel free to [raise a discussion](https://github.com/nuxt/framework/discussions) for help. But you may need to provide some more info about what you have tried and what specifically isn't working.
