### ISSUE TITLE
dev server host 0.0.0.0 not available with Docker (Windows WSL)

### ISSUE THREAD

**Issue by Hemric** [nuxt/framework#2338]
## Environment
Operating System: Windows 10 / WSL 2 - Ubuntu 20.04
Node Version: v16.13.0
Nuxt Version: 3.0.0-27296172.f5307f9
Package Manager: yarn@1.22.15
Bundler: Vite
User Config: css, vite, typescript
Runtime Modules: -
Build Modules: -

## Reproduction 

```
npx nuxi init nuxt3-app
cd nuxt3-app
yarn install
yarn dev --port 4000 --host 0.0.0.0
docker run --add-host=host.docker.internal:host-gateway curlimages/curl:latest host.docker.internal:4000
```

## Bug
I'm trying to start the dev server with **nuxi dev --port 4000 --host 0.0.0.0** to have a docker container accessing it. 
I'm supposed to get the page content, i get a network error instead. This bug only occurs in windows wsl not with linux

## Additional context
I need this to work for our local dev environment that includes several nuxt app behind a nginx reverse proxy using https in a docker container.
On linux it's working properly but not with windows wsl 2.
It worked with webpack dev server in nuxt 2.

## Logs
``` curl: (7) Failed to connect to host.docker.internal port 4000 after 2024 ms: Connection refused ```

**Comment by peteromano** [comment]
This isn't a nuxt issue. `docker run` here needs --network=host, but it's usually bad practice to use the host network. Why not put Nuxt in a container as well, and have 2 containers using the docker bridge network (or even better, their own network)?

**Comment by Louis-Tian** [comment]
This is somewhat related to Nuxt issue. Perhaps not a bug but likely to do with how vite handles connections.
`--network=host` is not available for Docker for Windows and that's why `host.docker.internal` is needed to communicate with the host network.
I am migrating from Nuxt2. I have the Nuxt 3 and express api server running on different ports and an Nginx reverse proxy running in docker for CORS.
I can reach the API just fine from within the nginx container but got a connection refused from Nuxt server. At the same time, the Nuxt works perfectly from host directly.

**Comment by Louis-Tian** [comment]
Figure out the problem.
By default Vite only binds to the localhost and therefore is not reachable from `host.docker.internal`.
add the following to `nuxt.config.ts` to bind to all interfaces.
```
 vite: {
    server: {
      host: true,
    },
  },
```
