### ISSUE TITLE
after update have problems 3.0.0-27313139.1c88580  →  3.0.0-27324955.23397e6 

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#2410]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27324955.23397e6`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.6`
------------------------------

### Reproduction

Directory import '/Users/Desktop/s- /.output/server/node_modules/@heroicons/vue/solid' is not supported resolving ES modules imported from /Users/Desktop/s- /.output/server/chunks/app/server.mjs

### Describe the bug

after update 3.0.0-27313139.1c88580  →  3.0.0-27324955.23397e6  project build return errors.

and  WARN  @vueform/multiselect is incorrectly packaged. Please contact the package author to fix.

**Comment by danielroe** [comment]
It seems the issue is that `@vueform/multiselect` is incorrectly packaged. I would recommend raising an issue in their repository. See https://github.com/vitejs/vite/pull/6086 for a little more info, and you might find https://v3.nuxtjs.org/concepts/esm/ helpful too.

If you think there is also an issue with Nuxt, would you provide a reproduction? 🙏
