### ISSUE TITLE
Underscore in layout name is converted to hyphen

### ISSUE THREAD

**Issue by tony19** [nuxt/framework#2518]
### Environment

```
Nuxt CLI v3.0.0-27265876.3cd4494                                                                   17:38:51
RootDir: /home/projects/nuxt3-custom-layout                                                        17:38:54
Nuxt project info:                                                                                 17:38:54

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                   17:38:54

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

### Reproduction

https://stackblitz.com/edit/nuxt3-custom-layout?file=pages%2Fblog%2Findex.vue

### Describe the bug

In Nuxt 2, the layout names matched the filename exactly, but Nuxt 3 converts the underscores in the filename to hyphens.

 * [Nuxt 2 demo (layout name matches filename)](https://stackblitz.com/edit/nuxt-custom-layout?file=pages%2Fblog%2Findex.vue)
 * [Nuxt 3 demo (layout name replaces underscore with hyphen)](https://stackblitz.com/edit/nuxt3-custom-layout?file=pages%2Fblog%2Findex.vue)

Trying to use the filename (containing underscore) as the `layout` option in a page causes this error:

```
layout.mjs:15 Invalid layout `test_layout` selected.
```

If this is by design, I think that needs documentation. I don't see it in [the Layouts docs](https://v3.nuxtjs.org/docs/directory-structure/layouts) or [the Migration docs](https://v3.nuxtjs.org/getting-started/migration#nuxt-2-to-nuxt-3).

**Comment by GadQ** [comment]
It's because when resolving layouts names are transformed to kebab-case:
https://github.com/nuxt/framework/blob/11becef7355c9da668603a1e0129024d22a74ab1/packages/nuxt3/src/pages/utils.ts#L223

But when layout is applied it's name isn't transformed:
https://github.com/nuxt/framework/blob/694e95b2b436d23a492d207a894801f7e58b6cbb/packages/nuxt3/src/pages/runtime/layout.ts#L14

What would be preffered way of fixing this? 
1. Transforming name in both places (I guess someone used kebab-case for a reason)
2. Remove transform in resolveLayouts so layout property should always match name of the file
