### ISSUE TITLE
WARN Disabling duplicate auto import 'useRoute'

### ISSUE THREAD

**Issue by agrabsi** [nuxt/framework#2617]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/agrabsi/github-efcanj

just yarn install && yarn dev

then go to the composables directory and open the useFoo.ts
edit the file and save.

Vite reloads and the warnings appear

### Describe the bug

When creating a composable .ts file in the composables directory. I get these warnings in the console.

``WARN  Disabling duplicate auto import 'useRouter' (imported from '/home/*******/*******/node_modules/nuxt3/dist/pages/runtime/composables')``

``WARN  Disabling duplicate auto import 'useRoute' (imported from '/home/*******/********/node_modules/nuxt3/dist/pages/runtime/composables')``

Is this the desired behavior? What does it mean as I don't use the useRoute or useRouter composable in my application.

Thanks !

**Comment by K-Honkawa** [comment]
useRouter and useRoute and other functions work fine.

This is because the second and subsequent [updateAutoImports](https://github.com/nuxt/framework/blob/ca9761df9e22b54207321f1c9b3f997ad331e3c5/packages/nuxt3/src/auto-imports/module.ts#L76) will run when you change the composables directory. 
At this time, register the function such as useRouter again. 
[Deduplication will be done.](https://github.com/nuxt/framework/blob/ca9761df9e22b54207321f1c9b3f997ad331e3c5/packages/nuxt3/src/auto-imports/context.ts#L36)
