### ISSUE TITLE
useAsyncData can't block render layouts

### ISSUE THREAD

**Issue by huuhait** [nuxt/framework#2664]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-tgxmtm?file=pages%2Ftest.vue

### Describe the bug

In v2 asyncData can block all
but in v3 if i put another layout for pages have useAsyncData it still change route and layouts...

**Comment by Tahul** [comment]
Hello @danielroe ;

I think this is related to the point we discussed, the reproduction seem to show layout shifts unrelated to any CSS framework.

The layout seem not to be updated at the same time as the rest of the page content.

**Comment by danielroe** [comment]
The current behaviour on route change is:

* layouts resolve their async setup/asyncdata and render themselves
* then their children, including pages, resolve their async setup/asyncdata and render themselves

If this isn't the desired behaviour, I'd welcome any thoughts on what better behaviour could be, and (in particular) why it would be better.

Bear in mind that layouts & pages are deliberately being separated (see https://github.com/nuxt/framework/issues/2074), so it's likely to be quite tricky to prevent loading layouts until page async setups resolve. If you want to implement a blocking layout at the present moment, you can always do so by including `<NuxtLayout>` within your page rather than in `app.vue`
