### ISSUE TITLE
Vite plugin order

### ISSUE THREAD

**Issue by KaelWD** [nuxt/framework#2798]
### Environment

```
Nuxt CLI v3.0.0-27375427.d07d572
RootDir: /home/kael/Documents/vuetifyjs/test-projects/nuxt3/nuxt3-app
Nuxt project info:
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `yarn@1.22.5`
- Bundler:          `Vite`
- User Config:      `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

```ts
import { defineNuxtConfig } from 'nuxt3'
import vuetify from '@vuetify/vite-plugin'

export default defineNuxtConfig({
  css: ['vuetify/styles'],
  vite: {
    plugins: [
      vuetify(),
    ]
  }
})
```

### Describe the bug

`@vuetify/vite-plugin` needs to be placed *after* `@vitejs/plugin-vue` so it can process the output of the vue plugin, but the vite config in nuxt.config.ts is merged before the default config instead so the vuetify plugin just gets raw vue files.

**Comment by danielroe** [comment]
You may be able to achieve what you want with the `vite:extendConfig` hook, which will let you manipulate the order of the plugins.

**Comment by antfu** [comment]
I guess you can still change the plugin order with Vite's resolveConfig hook. Ideally, a plugin should not be order sensitive, otherwise, it should use the `enfore` option that Vite provides.  Since Vite offered a way to manipulate the order, while it's also possible to use the Nuxt hook in the module to have the order. I feel that having this fine-grained control directly in the config would be a bit out-of-scope. Closing for now.
