### ISSUE TITLE
How  <Style> or useMeta style works with dynamic values ?

### ISSUE THREAD

**Issue by anish2690** [nuxt/framework#2899]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.0`
- Nuxt Version:     `3.0.0-27383920.81ee59c`
- Package Manager:  `yarn@1.22.11`
- Bundler:          `Vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```tsx
<template>
  <div>
    <div id="test">Haill</div>
    <Style type="text/css">{{ style }}</Style>
  </div>
</template>
<script setup lang="ts">
const style = `#test { color: red; }`;
<script>
```
![image](https://user-images.githubusercontent.com/22445409/150916581-35f743a1-1b2b-41f2-a968-0271a8707699.png)

**It works when style p get passed like string** 

```tsx 
<Style type="text/css">#test { color: red; }</Style>
```

### Describe the bug

Dynamic injection of styles are broken in useMeta() or using new Meta components.

**Comment by danielroe** [comment]
This is an [upstream Vue behaviour](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxkaXYgaWQ9XCJ0ZXN0XCI+SGFpbGw8L2Rpdj5cbiAgICA8U3R5bGUgdHlwZT1cInRleHQvY3NzXCI+e3sgc3R5bGUgfX08L1N0eWxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuY29uc3Qgc3R5bGUgPSBgI3Rlc3QgeyBjb2xvcjogcmVkOyB9YDtcbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vc2ZjLnZ1ZWpzLm9yZy92dWUucnVudGltZS5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==) because `style` is a reserved tag - feel free to raise an issue there.

You can handle this, however, by passing `:children="style"` as a prop on `<Style>`.

**Comment by anish2690** [comment]
@danielroe Thanks for clarifying it. `<Style type="text/css" :children="styleString"></Style>` worked for me.
