### ISSUE TITLE
vite HMR Broken for <template> 

### ISSUE THREAD

**Issue by fanckush** [nuxt/framework#3006]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27389502.88da719`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `vite`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Not needed 

### Describe the bug

Changes to CSS are picked up immediately and it was the same to the rest but ever since I upgraded Nuxt3 yesterday (not sure which version I had before) template changes aren't picked up by and HMR is broken for them

**Comment by fanckush** [comment]
I was having other strange issues so I deleted yarn.lock and reinstalled all the dependencies. Now if I change anything in the `<template>` the whole component gets **misplaced** and gets pushed back to the bottom and below other components, very strange behaviour..

**Comment by toniengelhardt** [comment]
Hey @fanckush, I had a similar issue. The problem was that I'm using `pinia-plugin-persistedstate`, which uses data from `localstorage` to render the page. This obviously causes problems when trying to render the page server-side. The solution was to wrap everything in the template that relies on local browser data or the `window` or `document` objects in a `<ClientOnly>` tag. That resolved the issue for me.

**Comment by fanckush** [comment]
@toniengelhardt thanks! 
I'm actually using my own custom state (which also uses localStorage for persistence) i'll try your workaround until a fix is introduced
