### ISSUE TITLE
useAsyncData and useFetch run twice if page uses layout

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/framework#3168]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27408103.b243891`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://github.com/lukaszflorczak/nuxt3-demo/tree/test/fetch (branch `test/fetch`).

1. Run the `/` page and check console logs
2. Go to `index.vue` and set `layout: false` in `definePageMeta()`
3. Refresh the page

### Describe the bug

Today I noticed that `useAsyncData` and `useFetch` run requests twice – both server and client-side. I tested it in component and page. 

During my investigation, I found, that the problem exists only if the page uses a layout.

Probably it's related to https://github.com/nuxt/framework/pull/3011

**Comment by alancolant** [comment]
Same problem here

**Comment by Tahul** [comment]
Hello!

We experience the same issue in @nuxt/content docs theme, to lighten the investigation I also built reproduction on StackBlitz.

You can see there that on first page load, the random integer will be refetched on client side and the data fetched server side won't be preserved.

https://stackblitz.com/edit/nuxt3-repro-utzcxx?file=pages%2F[...id].vue

**Comment by danielroe** [comment]
This seems to be an upstream issue: see https://github.com/vuejs/router/issues/626#issuecomment-1048609550

**Comment by fazulk** [comment]
@danielroe - I noticed this as well, So i removed layout and the issue was resolved. _Although_, once i introduced a second API call using `useAsyncData` the issue returned, but only for one of the API calls. 

```
<script setup>
const { data } = await useAsyncData("count", () => $fetch("/api/counter"));

// this will run both serverside AND browser side
const { data: secondCounter } = await useAsyncData("secondCount", () => $fetch("/api/counter-2"));
</script>

```

**Comment by Baiyuetribe** [comment]
I did the same thing with the backend written in golang, using useFetch or useAsyncData to request api, both triggered twice.This problem needs to be solved urgently

**Comment by danielroe** [comment]
@Baiyuetribe From what you've said, it's possible your browser is requesting a favicon along with the HTML request.

If you don't have a pages directory or a favicon, Nuxt will respond to both requests with a full HTML page, which means you will get two asyncData requests to your API.

The specific bug here seems to be upstream in Vue, triggered by having nested `Suspense` components, either because of a layout wrapping a page or a page wrapping a child page (on a nested route)...

**Comment by Baiyuetribe** [comment]
@danielroe I'm not talking about the icon problem, I use golang to develop the back-end api interface and then use nuxt3 to call the api to achieve server-side rendering. Even in the minimal demo, the request is triggered twice.In the default `app.vue`
```app.vue
<template>
  <div>
    <h3>{{ data }}</h3>
  </div>
</template>

<script setup>
const { data } = await useFetch('http://192.168.1.3:363/api/home', { server: true }) 
</script>
```
I think the first time the usefetch may have worked, the second time it may have been triggered by `entry-xxx.mjs` from the client.
![image](https://user-images.githubusercontent.com/43716063/155768510-74187130-ecce-4634-86db-eef34fda3cc0.png)

**Comment by danielroe** [comment]
@Baiyuetribe Would you provide a reproduction? I'm still thinking the issue in _your_ case is the extra favicon request.

**Comment by alancolant** [comment]
@danielroe I provide a reproduction here:
[Repro](https://stackblitz.com/edit/nuxt3-repro-de1dhp?file=pages/index.vue)

**Comment by Baiyuetribe** [comment]
@danielroe sandbox https://stackblitz.com/edit/github-5qtamp?file=app.vue
Just run `yarn build && yarn start` or `yarn dev` as well
![image](https://user-images.githubusercontent.com/43716063/155827808-8ae9a177-1bc4-4117-8e86-2e5d7efd0477.png)

You can see that after one server-side request, the client will request it again. So it causes two requests.

**Comment by danielroe** [comment]
@Baiyuetribe Your issue is unrelated to this particular thread.

The cause is your browser requesting `favicon.ico` automatically. Because this file doesn't exist, and you are handling all requests with `app.vue` (rather than using a router) this means you will receive two requests to your Nuxt server for every single reload in your browser.

As a consequence, you will receive two requests to your API. That can easily make you _think_ that it's running twice, even though it is only running once per render. It is easily solved by adding a `~/public/favicon.ico` file. (Longer term, we are likely to add a default 1px transparent ico to avoid this issue, but that is pending https://github.com/nuxt/framework/issues/3161.)

<img width="889" alt="CleanShot 2022-02-26 at 13 13 25@2x" src="https://user-images.githubusercontent.com/28706372/155844663-a1a7959e-a226-4d61-84b1-6023d155159f.png">

**Comment by Baiyuetribe** [comment]
@danielroe Thank you very much. It works fine after adding favicon.ico. Highly recommend adding it to the template, I almost gave up because of this problem.

**Comment by Baiyuetribe** [comment]
![image](https://user-images.githubusercontent.com/43716063/155874940-10763d37-3ff2-4f03-8fa8-6b64efd0580d.png)

After fixing the icon issue,When there are layouts, it does lead to a second request from the client, and the problem can lead to repeated rendering of the page
@danielroe  sandbox https://stackblitz.com/edit/github-5qtamp-u2ftnu?file=pages/index.vue

**Comment by danielroe** [comment]
@Baiyuetribe Please see https://github.com/nuxt/framework/issues/3168#issuecomment-1048609912.

**Comment by Baiyuetribe** [comment]
@danielroe When useFetch parameter server: true, can the client block the request?
Or is there any temporary solution? Not solving the problem will lead to duplicate requests and rendering of page data, and the worst will lead to secondary requests with errors.

**Comment by Baiyuetribe** [comment]
Temporarily, I found that after deleting the layouts file, simply using pages is normal.
Hope to modify the duplicate rendering problem caused by layouts soon

**Comment by Baiyuetribe** [comment]
@danielroe sandbox https://stackblitz.com/edit/github-5qtamp-82ca6q?file=app.vue
New solution, delete `layouts` and put the contents in `app.vue` and everything is back to normal. It seems the problem can only be with `layouts`.
![image](https://user-images.githubusercontent.com/43716063/155880895-aab44e85-57b2-421f-80e8-415276f7b31e.png)

**Comment by danielroe** [comment]
@Baiyuetribe The problem does not seem to be with Nuxt but with `Suspense`, which is why I linked my comment above, and why this is labelled `upstream`.

**Comment by djschilling** [comment]
@danielroe if it is an upstream problem, could you then use an older version of vue-router in the current version of nuxt, so that we can use the newest version of nuxt?

**Comment by danielroe** [comment]
The problem seems to be inherent in nested `<Suspense>` with dynamic components, which is used in NuxtLayout and NuxtPage. I can see if there is a workaround we can adopt, but the aim is to fix this in Vue core.

**Comment by mjrobinson86** [comment]
@danielroe, I actually seem to have this issue regardless of whether or not I am using layouts. From the comments there seems to be an upstream issue so perhaps it's not the right forum to mention it... but even with the latest beta update I get the double call.

I'm running an apollo client query inside of the useAsyncData handler and it all seems to work in terms of SSR, hydration seems to be successful etc... so not sure its something irregular in my test app at least.

Great work with this project in any case, really excited to use the production version... a vast improvement on an already capable platform. :)

**Comment by danielroe** [comment]
@mjrobinson86 Thanks for the kind words! Any chance you could create an issue with reproduction? Might also be worth checking https://github.com/nuxt/framework/issues/3890 to see if this describes your issue.

**Comment by serhez** [comment]
I'm having this issue as well (nuxt3 + Golang backend). I'm using layouts, pages, a favicon and `useFetch` with the `server: true` option (which I believe it's true by default, anyway). One of the requests seems to be made from the client and the other one from the server (I don't know if this matches what has been stated in this issue, from what I read you are talking about both being made from the server); is this normal given the problems stated in this issue?

From reading @danielroe, it seems this is not solvable at a Nuxt level, but it is quite critical if you are making requests to an API which has side effects (e.g., a request which deletes data from a DB), which seems to me like quite a common case. Hopefully we can see it solved, because we'll have to default to using regular `fetch` otherwise.

PS: Thanks for your work on the project 🙏🏻

**Comment by serhez** [comment]
To expand on my previous comment:

I've tried a few things, hopefully you can make sense of it all (I haven't been able to 😬 ):
- Having a `useFetch` call when I have CORS configured in my Golang API server generates 2 calls to the API server, both successful. Doing `if (process.client) console.log(...)` just after fetching prints the correct fetched data in the console, which makes me think one of the calls is done client-side.
- When I remove the CORS config from the API and refresh the page, I see in the client console errors about CORS and `console.log` now prints `null`, which I think confirms one of the calls is done client-side (?). Also, now 3 calls are made to the API server 🤯 .

**Comment by codelegant** [comment]
Have same issue，here is my solution https://github.com/Baiyuetribe/nuxt3-naive-ui-starter/issues/9#issuecomment-1085624092

**Comment by danielroe** [comment]
Any lingering double-fetches should be resolved in https://github.com/nuxt/framework/pull/3985. Please open a new issue with a reproduction if you still experience this on the latest version of Nuxt. 🙏

**Comment by serhez** [comment]
@codelegant I've tried the fetching with `if (process.server)` as well as with Vue's `onServerPrefetch()` hook, but doing this introduces a lot of hydration mismatches for me, since you need to copy the async data to an existing `ref`. There is most certainly a good way to do it, possibly with a `watch` or something, but I haven't found it 😞

**Comment by serhez** [comment]
@danielroe thanks for the info, I am not on the latest version. I might as well wait until the RC is released (7th of this month? 🙏🏻 ) to upgrade. I'll probably forget to post here when I upgrade if the issue is fixed, but then you can assume it is 😛

**Comment by codelegant** [comment]
> @codelegant I've tried the fetching with `if (process.server)` as well as with Vue's `onServerPrefetch()` hook, but doing this introduces a lot of hydration mismatches for me, since you need to copy the async data to an existing `ref`. There is most certainly a good way to do it, possibly with a `watch` or something, but I haven't found it 😞

The async data no need fetching in server.

**Comment by mjrobinson86** [comment]
@danielroe this solved my problem perfectly, so I think the core issue is resolved at least as far as I can tell.

**Comment by engvie** [comment]
I made a reproduce of this issue:

**Comment by engvie** [comment]
I made a reproduce of this issue:

https://stackblitz.com/edit/github-o71jez-c7i3aw?file=pages/index.vue

Multiple console.logs of same page.vue

**Comment by engvie** [comment]
> I made a reproduce of this issue:
> 
> https://stackblitz.com/edit/github-o71jez-c7i3aw?file=pages/index.vue
> 
> Multiple console.logs of same page.vue

My mistake.
The problem was that I used <NuxtPage> inside the layout instead of using <slot />

**Comment by NidMo** [comment]
> @Baiyuetribe The problem does not seem to be with Nuxt but with `Suspense`, which is why I linked my comment above, and why this is labelled `upstream`.
> 
> This issue exists, at the moment, to track the resolution of the issue within vuejs/core or vue-router.
> 
> If you spot an issue with the way layouts or pages are implemented in Nuxt, of course I would be very glad to hear that.

if page uses layout, child page will setup twice

**Comment by nathanchase** [comment]
I'm on "nuxt": "3.0.0-rc.5", and I'm still seeing this same behavior. All useFetch (or $fetch) calls occur twice - once SSR, and again on client. It doesn't matter if I am using a layout or not.

**Comment by danielroe** [comment]
@nathanchase would you create a new issue with a reproduction? 🙏

**Comment by nathanchase** [comment]
> @nathanchase would you create a new issue with a reproduction? 🙏

It appears to be pinia at fault. If I delete pinia from my modules in nuxt.config, useFetch/$fetch no longer loads data twice.

I'm using "@pinia/nuxt": "^0.3.0", and "pinia": "^2.0.16".

Will try to create a barebones repro.

**Comment by nathanchase** [comment]
@danielroe False alarm. It was a matter of data being pushed into an array errantly inside a for loop inside a store action.

**Comment by satriaajiputra** [comment]
Have same issue. This issue happens when I use a reactive variable i.e route or pinia store. The useFetch will be executed twice when moving to another page. In my case, when I'm in a blog post and move to blog page.

```ts
const route = useRoute()
const { data } = await useFetch<Response>(`/api/blog/${route.params.slug}`)
```

When I'm testing with a hard code url and trying to move to another page, the useFetch not run in twice
```ts
const { data } = await useFetch<Response>(`/api/blog/hello-world`)
```

**Comment by devCrossNet** [comment]
Hey, I just came across this thread because I faced the same issue. When using a Pinia action within `useAsyncData` the action gets invoked twice (1st server, 2nd client).

I boiled it down to this issue:
Pinia actions don't return any data which leads to an empty cache (you can see this in this line: https://github.com/nuxt/framework/blob/main/packages/nuxt/src/app/composables/asyncData.ts#L113).

I wrote a wrapper composable to have a workaround that looks like this:

```ts
// Use this composable to prefill a store with an action
// Hack to make tell nuxt that this function was executed
export const usePrefillStoreAction = async (action: () => Promise<unknown>) => {
  await useAsyncData(async () => {
    await action();
    // TODO: create issue that Pinia somehow needs to return a value from the action?
    return Promise.resolve('true');
  });
};
```

Not sure if I need to file an issue on the Nuxt repo or Pinia repo.

Let me know what you think.

cc: @danielroe

**Comment by danielroe** [comment]
In this case you might even find it better to use the vue `onServerPrefetch` hook rather than using a side effect of `useAsyncData`, which we would generally recommend against.

**Comment by devCrossNet** [comment]
@danielroe my use case is pretty simple: I want to invoke a pinia action to get page-specific data whenever a user navigates to that page, either by visiting it directly or on client-side navigation. As far as the docs say and the name implies `onServerPrefetch` would only cover the case when the user directly visits the page and not on client-side navigation. Or am I getting this wrong?

In Nuxt 2 asyncData was sufficient for this basic use case.

**Comment by danielroe** [comment]
Yes, that's right.

**Comment by devCrossNet** [comment]
@danielroe what would be your recommended solution then? Not using Pinia?

**Comment by nathanchase** [comment]
> @danielroe what would be your recommended solution then? Not using Pinia?

The way I've done it is like so:
```ts
const { data: user } = await useAsyncData(username, async () => {
  await usersStore.getUser(username); // <- this is calling the getUser action from the usersStore
  return usersStore.user; // <- this returns the actual state value from the store once the above promise resolves
});
```

**Comment by devCrossNet** [comment]
@nathanchase good to know that this works. I will have a look and think about the pros and cons between your solution and mine. Thanks a lot 👍
