### ISSUE TITLE
Vite HMR port configuration is no longer honored

### ISSUE THREAD

**Issue by pierres** [nuxt/framework#3183]
### Environment

* nuxt3 3.0.0-27408580.aece351
* using Node 17 within a Docker container

### Reproduction

Configure the Vite HMR port via nuxt.config.ts

```js
    vite: {
        server: {
            hmr: {
                port: 9001,
                clientPort: 9001
            }
        }
    }
```

### Describe the bug

Vite will still use the default port 24678 for the web socket connection. This used to work in previous Nuxt3 version. My assumption is that the following commit introduced this bug: https://github.com/nuxt/framework/pull/3169/files

**Comment by misaon** [comment]
Is `clientPort` defined in `defineNuxtConfig > vite > server > hmr` respected at all? After updating to version `3.0.0-27408529.089160a` the page started reloading because it cannot connect to HMR. We have a rule in reverse proxy for websocket where there is a fixed port. If it is to be dynamic, **we cannot reasonably use Docker for local development !**
