### ISSUE TITLE
"mode" property is missing on TransitionProps interface

### ISSUE THREAD

**Issue by fmcdigital** [nuxt/framework#3255]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27404037.29171bd`
- Package Manager:  `npm@8.0.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `css`, `vite`, `dir`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```
    const pageTransitionProps = {
      name: 'fade',
      mode: 'out-in',
      css: true
    };

    router.currentRoute.value.meta.pageTransition = pageTransitionProps;
```

### Describe the bug

```
Type '{ name: string; mode: string; css: boolean; }' is not assignable to type 'boolean | { name?: string; type?: "transition" | "animation"; css?: boolean; duration?: number | { enter: number; leave: number; }; enterFromClass?: string; enterActiveClass?: string; enterToClass?: string; ... 20 more ...; onAppearCancelled?: (el: Element) => void; }'.
```

**Comment by danielroe** [comment]
The issue is that your object isn't typed, but Vue type-checks the `mode` property as being only a couple of specific strings (so the `string` type isn't specific enough).

![CleanShot 2022-02-16 at 13 34 33](https://user-images.githubusercontent.com/28706372/154275548-ed1e2a68-84e2-41f9-b1b8-6b4c42e1b39e.png)

Here's how to fix it:

```diff
  const pageTransitionProps = {
    name: 'fade',
    mode: 'out-in',
    css: true
- };
+ } as const;

  router.currentRoute.value.meta.pageTransition = pageTransitionProps;
```
