### ISSUE TITLE
API endpoint got called twice when the app boots up

### ISSUE THREAD

**Issue by ydcjeff** [nuxt/framework#3774]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27459267.f69126e`
- Package Manager:  `pnpm@6.32.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/ydcjeff/test-nuxt-3

### Describe the bug

API endpoint got called twice when the app boots up while I expect one time.

![Screen Shot 2022-03-18 at 17 28 57](https://user-images.githubusercontent.com/32727188/158991864-1f31f8fa-7ac8-4fc0-a7cd-90b9c96d0957.png)

**Comment by danielroe** [comment]
This is often because browsers make a request to get `favicon.ico`. If you don't have such a file in your `public` folder, or don't have a `pages` folder, Nuxt will serve this with `app.vue` as well, meaning you get two requests for each request.

See https://github.com/nuxt/framework/issues/2453 for our proposed solution to this.
