### ISSUE TITLE
broken route generation

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3892]
Hi @kevinmarrec, I created a simple example, try to navigate to /apis, /apps or /dbs. Only the first folder is resolved.
- https://codesandbox.io/s/lively-darkness-cd2x8c

_Originally posted by @wsaca in https://github.com/nuxt/framework/issues/3783#issuecomment-1078653201_

The routes generated are:

```js
export default [
  {
    path: '/apis',
    file: '/sandbox/pages/apis.vue',
    children: [
      {
        name: 'apis',
        path: '',
        file: '/sandbox/pages/apis/index.vue',
        children: [],
        component: () => import('/sandbox/pages/apis/index.vue'),
      },
    ],
    component: () => import('/sandbox/pages/apis.vue'),
  },
  {
    name: 'bd',
    path: '/bd',
    file: '/sandbox/pages/bd/index.vue',
    children: [],
    component: () => import('/sandbox/pages/bd/index.vue'),
  },
  {
    name: 'index',
    path: '/',
    file: '/sandbox/pages/index.vue',
    children: [],
    component: () => import('/sandbox/pages/index.vue'),
  },
]
```

**Comment by kevinmarrec** [comment]
@danielroe I'm gonna check, but I'm really wondering how the extends feature could have broken this.

If you check the `pages` extends PR you'll see that all I've done is applaying same logic to all layers instead of the first one.

Let's test this repro against different Nuxt 3 versions so we can find the culprit commit !
