### ISSUE TITLE
Import createRouter does not exist in h3 export

### ISSUE THREAD

**Issue by sasaorasanin** [nuxt/framework#4205]
### Environment

Nuxt CLI v3.0.0-27490192.4253d2e                                                                                                                     16:02:07
RootDir: C:\Users\Lenovo\Desktop\sat                                                                                                                 16:02:10
Nuxt project info:                                                                                                                                   16:02:10

- Nuxt Version:     `3.0.0-27490192.4253d2e`
- Package Manager:  `npm@8.1.4`
- Builder:          `vite`
- User Config:      `buildModules`, `css`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `nuxt-windicss@2.2.8`
------------------------------
Package error: 
h3 => v0.3.9

### Reproduction

I did a npm update and after it started showing the error on npm run dev. yesterday had no problems.

When I manually install "npm i h3" to the latest version it works.

### Describe the bug

 ERROR  [worker reload] [worker init] The requested module '__PROJECT__/node_modules/h3/dist/index.mjs' does not provide an export named 'createRouter'

  import { handleCacheHeaders, toEventHandler, createApp, createRouter, lazyEventHandler, eventHandler, useQuery } from '__PROJECT__/node_modules/h3/dist/index.mjs';
  ^^^^^^^^^^^^
  SyntaxError: The requested module '__PROJECT__/node_modules/h3/dist/index.mjs' does not provide an export named 'createRouter'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
  at async handleMainPromise (node:internal/modules/run_main:61:12)

**Comment by danielroe** [comment]
Thanks. We need to bump the version in `unstorage` (cc: @pi0).

In future I'd recommend running `npx nuxi upgrade` or `npx nuxi upgrade --force`.

**Comment by jiblett1000** [comment]
I'm getting this as well when switching from the tailwindcss module to the windicss module.

**Comment by sasaorasanin** [comment]
@jiblett1000 When I changed from tailwind to windicss I got some strange problems with @apply. It applied styles to elements I haven't even wrote anything to. Not sure why is it happening. Got pissed and just copied tailwind generated css 👎

**Comment by acidjazz** [comment]
Getting this as well - unable to continue on any projects after i run `yarn nuxi upgrade`

**Comment by michael-observerly** [comment]
I can confirm that this is also happening when upgrading to the latest version of nuxt.

**Comment by Louis-Tian** [comment]
Bumped into this as well. 
Looked into the problem for a bit and I think the problem lies with `nitropack` somehow importing `h3` from the wrong location.

The bug gets triggered when an older incompatible version of "h3" gets installed at the top level of `node_modules`

For example, in my case, I have the following dependency trees
`nuxt3 3.0.0-27491748.3186841` -> `h3 ^0.7.2`
`nitropack 0.2.1` -> `h3 ^0.7.1`
`nitropack 0.2.1` -> `unstorag ^0.3.3` -> `h3 ^0.3.3`
`nuxt-windicss ^2.2.8` -> `h3 ^0.3.9`

A clean npm install after removing `package-lock` and `node_modules` resulted in the following file structure.
```
node_module
├── h3 ^0.3.9 <-- nitropack is importing this at runtime which causes the problem
└── nitropack
        ├──node_module
        ├── h3 ^0.7.2
```
Nitropack is importing h3 from the top-level instead which causes the error.

A hacky fix one might try for now is to manually reinstall the packages in a prescripted order to force the h3 ^0.7.2 to be installed at the top level. That means installing nuxt3 first and then the other packages.
For example
- remove `package-lock.json` and `node_modules/`
- `npm install nuxt3@latest`
- `npm install windicss@latest`

**Comment by jiblett1000** [comment]
Should be fixed now. At least for windicss https://github.com/windicss/nuxt-windicss/releases/tag/v2.2.9

**Comment by danielroe** [comment]
Should be resolved in https://github.com/unjs/nitro/commit/ba2e237b5dc95ba9681dc33afd2e1898638e16f8.
