### ISSUE TITLE
`app:rendered` does not have rendered HTML result as argument, like nuxt2 had with `render:routeDone`

### ISSUE THREAD

**Issue by SebJansen** [nuxt/framework#4339]
### Environment

Nuxt CLI v3.0.0-27495135.4d1a6ba
RootDir: ...
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-27495135.4d1a6ba`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `buildModules`, `runtimeConfig`, `css`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `@unocss/nuxt@0.24.4`

### Reproduction

In Nuxt2, the hooks `render:route` and `render:routeDone` have the SSR'd result as an argument: https://nuxtjs.org/docs/internals-glossary/internals-renderer/

However in Nuxt3, there seems to be only the `app:rendered` hook, and it doesn't have access to the SSR'd HTML.

### Describe the bug

In order for caching to work at all under environments such as Cloudflare Workers, access to the raw HTML is necessary, in order to manually store it for future use.

This is because CF Workers sit in front of CF CDN: https://developers.cloudflare.com/workers/runtime-apis/cache/

Nuxt 3 does not currently seem to have a hook that allows access to raw SSR'd HTML, which stops production-use of Nuxt 3 when there is a need for caching content.

**Comment by pi0** [comment]
Nuxt 3 architecture is different in that server is entirely part of the runtime. `server:` hooks are not possible like Nuxt.

Would you please explain better your setup? Were you using `nuxt generate` and populating CF cache manually?

**Comment by SebJansen** [comment]
## Architecture

Does the Nuxt 3 architecture stop the `app:rendered` hook from being able to pass the SSR'd raw HTML content to the lambda function? If so, then it's clearly not a bug, and I'm sorry for spamming another issue so I would close this. If it is possible however (and depending on difficulty), I would strongly argue for the SSR'd raw HTML to be passed as an argument, because caching is a critical use case and the absence of the hook appears to make certain things impossible.

## Context

### Nuxt 2
I wasn't using `nuxt generate`, all SSR but with caching applied. In Nuxt 2 self hosted, I had it set up to cache through Redis


### Nuxt 3
With Nuxt 3, I'm deploying to the Cloudflare Workers serverless runtime. There is no automatic caching mechanism on Cloudflare Workers however. This means that on server side, I need some way to manually store the raw HTML in the Cloudflare Cache, in order to make it feasible to run the project on Cloudflare. Otherwise, every request will incur a full render, which increases the bill substantially and adds a ton of latency to the user.   

If I were to deploy the Nuxt 3 project to Vercel or Netlify, the SSR'd responses would be cached by their platform, through the `Cache-Control` headers, all perfect and transparent. However, Cloudflare Workers don't work this way because Workers are expected to manually get and put raw HTML through the Workers Cache API due to the traditional CDN caching-mechanism not applying to workers.

**Comment by clairegraham** [comment]
Pretty sure I hit this same issue, which explains why static assets like *.mjs, *.js, and *.css are cached properly, but Cloudflare will never cache a Nuxt 3 HTML response, even if page rules are configured appropriately on Cloudflare's end to cache everything. The same configuration works fine with any other site, including a Nuxt 2 one, but it does not work with a Nuxt 3 site with the same configuration.

As @SebJansen pointed out, this makes using a Nuxt 3 project on Cloudflare Workers a lot less desirable as every single page request will require a worker request to render the page, instead of being able to depend on the Cloudflare CDN for cached resources. This dramatically increases the total cost.

Huge bummer as this is now a blocker to launching our new site, which I just finished rewriting/refactoring from Nuxt 2 -> Nuxt 3.

**Comment by danielroe** [comment]
This is now possible with the nitro `render:html` and `render:response` hooks. See https://github.com/nuxt/framework/pull/6521.
