### ISSUE TITLE
Module not accept typescript path alias

### ISSUE THREAD

**Issue by TrungRueta** [nuxt/framework#4374]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27498764.32c798c`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `typescript`, `buildModules`, `components`, `windicss`, `autoImports`, `router`, `experimental`, `features`, `globalName`, `build`, `vite`, `loading`, `cli`, `alias`, `privateRuntimeConfig`, `publicRuntimeConfig`, `css`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.2.6`, `nuxt-windicss@2.2.11`, `~/modules/test.ts`
------------------------------

### Reproduction

- create new fresh nuxt
- create new file `lib/test.ts`
```typescript
export const testLib = {
  ok: true,
};
```
- create new file `modules/test.ts`
```typescript
import { defineNuxtModule } from '@nuxt/kit';
import { testLib } from '~~/lib/test';

export default defineNuxtModule({
  setup() {
    console.log('module inited');
    console.log(testLib);
  },
});
```
- input module into `nuxt.config.js`
```typescript
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  modules: ['~~/modules/test.ts'],
});
```

run project and see error not found file lib from `~~/lib...`

### Describe the bug

This is repo test
https://stackblitz.com/edit/github-fjh4sx-bfb1gj?file=nuxt.config.ts

**Comment by danielroe** [comment]
This will likely depend on https://github.com/unjs/jiti/issues/37. At the moment, aliases do not apply within modules as they are not processed by either rollup, vite or webpack but rather loaded with `jiti`.

**Comment by pi0** [comment]
For **static imports** in both nuxt module and `nuxt.config`, I would highly recommend you to use valid Node/ESM import paths such as `import from '../lib/test'` or `import from '<packagename>'` or `import from '#alias'` using import maps (*)

Module and nuxt config are normal node modules with a lightweight transform-only loader provided by jiti for typescript syntax support. But jiti, same as Node is unaware of tsconfig and nuxt aliases. This is by design to keep them standard modules.

Alias support using import maps: 


`package.json`:

```json
{
  "type": "module",
  "imports": {
    "#test/utils": "./test/utils.ts"
  }
}
```

`nuxt.config`:

```
import hello from '#test/utils'

console.log(hello)
```

One extra thing you can do within modules, are utilities from `@nuxt/kit` for **dynamic imports** and path resolution that can benefit fully from aliases using `import { resolvePath } from '@nuxt/kit'`. Kit utilities and module runtime is running in context of nuxt and aware of possible aliases.

----

> @danielroe  This will likely depend on https://github.com/unjs/jiti/issues/37. At the moment, aliases do not apply within modules as they are not processed by either rollup, vite or webpack but rather loaded with jiti.

Off topic: Nuxt config (that includes nuxt aliases) is loaded before nuxt and the upstream feature of jiti is mostly programmatic. (not intending to depend on global files like `tsconfig` to infer aliases.) We can introduce some basic `~` and `@@` aliases however with jiti but even that depends on IDE support and one-time preparation and making both files less standard modules. I proposed that issue for other purposes. However, jiti is already using native node resolution and supporting import maps 🤞🏼

**Comment by AlansCodeLog** [comment]
So I think I ran into this issue. I have a component library an nuxt app depends on. The docs [here](https://nuxt.com/docs/guide/directory-structure/components#library-authors) say one can just add a nuxt.js file, point it to the components and done.

The library appeared to load fine at first. But when I imported components that imported other components, they failed if they used aliases. The aliases from the component library were getting resolved by the aliases in the nuxt app, so nuxt was searching in _nuxt/components instead of the library's components folder.

I tried switching the component lib to use import maps, but this does not work, nuxt says vite failed to resolve the import paths. 

If on the other hand I declare my own plugin to add/use the library, then it works, but I loose all typing info, which I know how to fix but :weary:

Will nuxt/jiti support resolving at least import paths when a module is in a package? or am I doing something wrong here? Is there some way around this?
