### ISSUE TITLE
Unable to disable Vite HMR

### ISSUE THREAD

**Issue by sharifzadesina** [nuxt/framework#4570]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Doesn't matter.

### Describe the bug

Hello,

```js
export default defineNuxtConfig({
  vite: {
     server: {
       hmr: false
     }
  },
});
```

This config is supposed to disable HMR, but when merging it seems it doesn't respect the `hmr: false` value and just uses the default config.

**Comment by danielroe** [comment]
This seems to work for me: https://stackblitz.com/edit/github-ij4eox-j1gxhd.

Let me know with a reproduction if you are still encountering this aand I'll reopen

**Comment by HendrikJan** [comment]
@danielroe This problem seems still to exist. Here is how to reproduce:

__Reproduction:__
If you look at your reproduction: : https://stackblitz.com/edit/github-ij4eox-j1gxhd.
Then you can see these two lines in your browser console: 

```
client.ts:16 [vite] connecting...
client.ts:53 [vite] connected.
```

So Vite hmr is still trying to connect.

In case you try to disable hmr because you cannot get it to work (ssl behind a reverse proxy for instance), then your console fills with errors and the site to constantly reload.
