### ISSUE TITLE
Support auto-imports when using `extends`

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#5027]
When extending projects in `node_modules`, auto-imports are not injected automatically. We can use https://github.com/unjs/unimport/blob/a2a2951c8a62866b7a2f6a88202de62b8d3a7355/src/unplugin.ts#L18 to do so, improving DX.

**Side-note**: as part of https://github.com/nuxt/module-builder we could possibly run a compile-time step to process auto-imports into an explicit import from '#imports'...

**Comment by antfu** [comment]
What's your plan for it? Should we add the include automatically inherit from the `extends`? If so I think it makes sense.

Regards on module builder, I actually think it's better for a library/module to use explicit imports from `#imports` or somewhere rather than relying on the auto-import. But if we want, I think it would be straightforward to implement with unimport.
