### ISSUE TITLE
Auto Import won't work for Local files

### ISSUE THREAD

**Issue by Bradley-H** [nuxt/framework#5053]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `head`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I have a Components folder with 1 folder, inside that there is, Burger and Navigation.

Inside Navigation, I have the burger. However, I can't get the burger to work without using the import statement.

I think it has something to do with it being local, like in the same folder. Because inside my Index page I can bring in the Navigation component (that houses my burger) and it works just fine.

![123](https://user-images.githubusercontent.com/37282160/169196608-6ff17b0e-3be7-48dc-98d3-f6b3bbf20923.png)

### Describe the bug

Won't auto import local files

**Comment by jiblett1000** [comment]
@Bradley-H If burger is inside `components/Navigation/Burger.vue`, it would be accessed as `NavigationBurger'

**Comment by jiblett1000** [comment]
@Bradley-H This is not a bug. Components are accessed using their full path. So, since burger is in `components/navigation/Burger.vue`, it would be accessed as `<NavigationBurger />`. However, If the child component has the the same words in it's name as the parent folder/folders, it would accessed as such. For example, your navigation component in `components/navigation/Navigation.vue` would be accessed as `<Navigation />` and not `<NavigationNavigation />`. I would suggest taking another look at the component docs... https://v3.nuxtjs.org/guide/directory-structure/components
