### ISSUE TITLE
url match strict for seo

### ISSUE THREAD

**Issue by suktec** [nuxt/framework#5119]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `router`, `css`, `typescript`, `modules`, `components`, `vueuse`, `unocss`
- Runtime Modules:  `@vueuse/nuxt@8.5.0`, `@unocss/nuxt@0.33.5`, `@pinia/nuxt@0.1.9`
- Build Modules:    `-` 

### Reproduction

https://stackblitz.com/edit/github-ty2wyb?file=nuxt.config.ts,app.vue

### Describe the bug

I used nuxt.config

```
router: {
    options: {
      strict:true
    }
  }

```
console error
`No match found for location with path "/art/a178/"`

my pages tree

```
pages
├── art
   ├── a[id]
       └── index.vue
   |──b[id].vue
```

I think "/art/a178/" should match the index.vue ,and "/art/b17" match the b[id].vue.
This is good for seo

Sorry for my poor English. Is the description clear.

**Comment by 516310460** [comment]
是否是 https://github-ty2wyb-pnqmje--3000.local.webcontainer.io/art/p123 能访问到index.vue

**Comment by 516310460** [comment]
> 是否是https://github-ty2wyb-pnqmje--3000.local.webcontainer.io/art/p123能访问到index.vue

而 https://github-ty2wyb-pnqmje--3000.local.webcontainer.io/art/p123/ 就能访问不到index.vue了？

**Comment by 516310460** [comment]
本地未复现出来，一切正常

**Comment by 516310460** [comment]
可能我用的是最新的代码，也许你可以等到 rc4 发布了，在看看。

**Comment by suktec** [comment]
> 可能我用的是最新的代码，也许你可以等到 rc4 发布了，在看看。

那坐等rc4发布了，感谢帮助。

**Comment by 516310460** [comment]
> > 可能我用的是最新的代码，也许你可以等到 rc4 发布了，在看看。
> 
> 那坐等rc4发布了，感谢帮助。

没事儿

**Comment by danielroe** [comment]
Setting `strict` doesn't default router to using trailing slashes - it only makes the router _care_ about it: https://router.vuejs.org/api/#strict.

If you want to force trailing slashes, you will need to use `pages:extend` to modify the paths generated by Nuxt to include a trailing slash. See an example implementation at https://stackblitz.com/edit/github-ty2wyb-8cl4ib.

**Comment by YuLogun** [comment]
Daniel, thanks for an example.

Perhaps, you could also suggest what should be done in my case:
My problem is that I do need slashes at the end of every path, but I don't want to show a 404 error if the user navigates to a path without a slash. I want to redirect the user to a path with slashes in that case.

As I understand, [redirect-module](https://github.com/nuxt-community/redirect-module) is not compatible with Nuxt 3.

What is the solution to implement redirect from a page without a slash to a page with it?

---
My current approach:
I removed `withTrailingSlash` and `router` option from `nuxt.config` and tried to use it in Nuxt route middleware (`middleware/redirect.global.ts`).

```
export default defineNuxtRouteMiddleware((to) => {
  if (!to.path.endsWith('/') && to.path !== '/') {
    return navigateTo(withTrailingSlash(to.fullPath, true), {
      redirectCode: 301,
    });
  }
});
```

Is it the way to do it?

**Comment by YuLogun** [comment]
@danielroe 
hi Daniel!
I have an addition to [my comment above](https://github.com/nuxt/framework/issues/5119#issuecomment-1216349117).

I assume you have read the comment and would really appreciate any advice.
The code in the middleware above does work and the redirect happens, however, I have a _concern_:

In my app I also have some other global middlewares (one that checks whether or not the user is authorized `auth.global.ts` and one that gets page meta data for each route from external api and updates pinia store `page.global.ts`).

When I console log inside them, I see that **all middlewares execute in spite of the fact that one of them redirects the user**.
This led to a **hydration error** after doing these 2 steps in browser:

1. Press Empty Cache and hot reload in Chrome (with open devtools)
2. Delete slash in the url and press Enter

The code that caused the hydration error:
`middleware/page.global.ts`
```
export default defineNuxtRouteMiddleware(async (to, from) => {
    const pageStore = usePageStore();

    const { data, error } = await getPageData(to.name);

    if (data.value) {
        pageStore.update(data.value);
    } else if (error.value) {
        pageStore.reset();
    }
});
```


`pages/cabinet/balance.vue`
```
const pageStore = usePageStore();
const pageTitle = computed<string>(() => pageStore.pageTitle);
...
<template>
....
 <div v-if="pageTitle" role="heading" aria-level="1" class="title-h2 mb-4">
      {{ pageTitle }}
  </div>
</template>
```

The solution I found was to rename `redirect.global.ts` to `0-redirect.global.ts`
I guess this changed the order of execution and somehow the hydration error disappeared.

Is there something wrong with my approach or is it a normal behavior?

**Comment by danielroe** [comment]
You're right, if you need to ensure that middleware runs first, the right approach is to add a numbered prefix.

**Comment by YuLogun** [comment]
@danielroe 
Hi Daniel!
Thanks a lot for your time and reply! It's invaluable.

The only thing that keeps nagging me in [the redirecting solution with route middleware](https://github.com/nuxt/framework/issues/5119#issuecomment-1216349117) is that **all other route middlewares always run** for both route from which we are redirecting and the route where we are redirecting. So, they execute twice.

For testing purposes, I set up a Nuxt 2 project with [redirect-module](https://github.com/nuxt-community/redirect-module) for redirecting from paths without slash at the end.
I found out that in this setup route middlewares do not fire for route without a slash (the one we are redirecting from).

Perhaps, it's because this module [uses server middleware](https://github.com/nuxt-community/redirect-module/blob/master/lib/module.js#L18) instead of a route middleware?

I then tried to perform a redirect via a server middleware in Nuxt 3 project and came up with the following code:

In `nuxt.config` I used the solution with `pages:extend` hook you provided [here](https://github.com/nuxt/framework/issues/5119#issuecomment-1174010456)

And my server middleware looks like this: `server/middleware/redirect.ts`
```
export default defineEventHandler(async(event) => {
    const decodedBaseUrl= decodeURI(event.req.url)
    const from = new RegExp('^(\\/[^\\?]*[^\\/])(\\?.*)?$')
    const toUrl = decodedBaseUrl.replace(from, '$1/$2')

    if (from.test(decodedBaseUrl)) {
        await sendRedirect(event, toUrl, 302)
    }
}) 
```

This set up works alright: `NuxtLink` routes to paths with slashes at the end and I also get a redirect on server side on the first page load without route middlewares firing.
I'm just worried that in the doc it is [stated](https://v3.nuxtjs.org/guide/features/server-routes#server-middleware) that server Middleware handlers should not return anything..

So, my question is: is it correct to perform such a redirect inside them? 

Perhaps, this discussion might also help someone else experiencing the same issue in the future
