### ISSUE TITLE
Can usefetch provide the immediate option？

### ISSUE THREAD

**Issue by 810505339** [nuxt/framework#5256]
### Environment

Operating System: Windows_NT
Node Version: v16.14.2
Nuxt Version: 3.0.0-rc.3
Package Manager: npm@8.5.0
Builder: vite
User Config: typescript, buildModules, vite, windicss, runtimeConfig
Runtime Modules: -
Build Modules: nuxt-windicss@2.3.1, @formkit/nuxt@1.0.0-beta.8

### Reproduction

![code](https://user-images.githubusercontent.com/50100966/171546234-2a0c8e25-f432-4444-8a5f-862453cc59f2.png)

### Describe the bug

```
const { execute } = useFetch(url, { immediate: false })

execute()
```

like this

**Comment by Luffyyy** [comment]
This would be pretty useful, I have to personally force this functionality via my own composable and would really prefer if Nuxt did it.

My use case is getting something that may not be needed always. In our site we have games and categories, if the game is selected then great, let's fetch categories, otherwise we have no categories to fetch, but useFetch will try to fetch them anyway and fail. There's no reason to ask the API something when we know for sure that it doesn't exist.

You could argue that I should fetch it elsewhere or do something else, but then I'll likely lose the nice SSR loading where everything is just loaded when you enter the page.
