### ISSUE TITLE
[definePageMeta] - Pinia (and possibly other modules) does not work inside the macro

### ISSUE THREAD

**Issue by xollaborator** [nuxt/framework#5864]
### Environment

Based on stackblitz:
```
Nuxt CLI v3.0.0-rc.4
RootDir: /home/projects/github-spvz4u
Nuxt project info:
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.2.1`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-spvz4u?file=pages%2Findex.vue

### Describe the bug

Below macro defined under repro link (line 76) doesn't work and prevents app from rendering. 
```
definePageMeta({
  title: useCounter().n,
});
```

The error message, defined by pinia, says:
```
[nuxt] [request error] [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
        const pinia = createPinia()
        app.use(pinia)
This will fail in production.
  at async eval (./.nuxt/dev/index.mjs:494:64)  
  at async eval (./node_modules/h3/dist/index.mjs:478:19)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:428:7)
```

But the app works correctly after commenting out line 76.

I've used Nuxt 3 with Pinia Demo link as a base for this repro. Pinia and its nuxt module were updated to most recent version. 

It is possible that the problem is on Pinia side but based on other bug that was fixed today I guess it might be not clear how to properly integrate both to enable all Nuxt features, like usage in this macro.

**Comment by Aareksio** [comment]
You are looking for `useHead` method. 

`definePageMeta` defines route's 'meta' key in `vue-router` and is, by design, unable to access component instance.

**Comment by Aareksio** [comment]
Pinia is added [via a plugin](https://github.com/vuejs/pinia/blob/v2/packages/nuxt/src/runtime/plugin.vue3.ts). Plugins are pieces of code that are executed on each render of the application. `definePageMeta`, on the other hand, is _compiler macro_, it is compiled away at build time.

This means that you can use imports:
```js
import { title } from '@/path/to/title'
definePageMeta({ title })
```

But can **not** access anything relying on to lifecycle of your application, because the macro is removed at build.

---

Someone from Nuxt team could probably let you know how to hook into the build process and create pinia instance there, but I honestly see no reason to do so - in the end you'd achieve the same result as hardcoding the values, in much more complicated way.

**Comment by xollaborator** [comment]
@Aareksio thank you for more detailed explanation. I started to wonder if this was actually working as expected using composable and it was not. So that totally makes no sense to aim at doing anything else with this macro. Have a great week.
