### ISSUE TITLE
Editable runtime config with HMR

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#5918]
Currently, providing [runtimeconfig](https://v3.nuxtjs.org/guide/features/runtime-config) from `nuxt.config`, `.env` and environment variables is possible but DX is not great because for each change, we need to restart Nuxt instance and there is no browser HMR.

We can introduce new `app.config.[ext]` (2) file that basically extends `runtimeConfig.app` namespace but is directly loaded by bundler (vite/webpack/nitro) and accepts hot module replacements and exposed as `useAppConfig()` / `$appConfig` (1). This file can also have more JS native types (non POJO).

```js
import { defineAppConfig } from 'nuxt/app'

export default defineAppConfig ({
  title: 'My Website',
  seo: {
    ogImage: '/og/card.png'
  },
  theme: {
    primaryColor: '#ababab'
  }
})
```

**Typing:**

Same as RuntimeConfig, types can be inferred directly from config and extended from `NuxtAppConfig` interface from `@nuxt/schema` by modules and theme layers

**HMR support:**

Since the idea is to add a virtual template and dependency to the bundlers, HMR is expected to work out of the box. But we can make it even better to toggle reactivity for `useRuntimeConfig()` ref in app.

---

1. Discussing with @Tahul, alongside with this feature, we might also introduce injected `$appConfig` for easier usage and access within templates.

2. Alongside with this feature, discussing with and by experience @nuxt/content-module team, there is a very common pattern to have a _theme_ configuration. I personally vote for the simplicity of having one `app.config` and `$appConfig` interface with `theme` subkey. But we can also introduce `theme.config` and `useThemeConfig()`/`$themeConfig` namespaced shortcuts from app config.

**Comment by Atinux** [comment]
I like the `app.config.ts` that is a nice place to start moving the `app` property from `nuxt.config.ts` to support HMR (I think it's also worth applying to `css` property for example).

```ts
export default defineAppConfig({
  css: ['~/assets/main.css'],
  head: {
    title: 'Hello World'
  }
})
```

Modules could also leverage this file for configuration related to the App side and avoid having to restart the whole server because of a change in `nuxt.config.ts`

Regarding the theme config, I believe this is at another level here since a Nuxt theme will define the config it needs for the logic it implements behind. But I like the logic of having it inside `useAppConfig().theme` with `useThemeConfig()` alias.

**Comment by pi0** [comment]
`css` config is nice idea. However, handling it would be a little more complex than the initial proposal. We need to extract it from runtime config with a custom watcher and provide it as an virtual file while it is already possible with `app.vue` to do this. I would add this feature alongside with `nuxt.config` HMR support (to avoid rebuild on `css` change but accept HMR to update virtual template)

**Comment by pi0** [comment]
> Regarding the theme config, I believe this is at another level here since a Nuxt theme will define the config it needs for the logic it implements behind. But I like the logic of having it inside useAppConfig().theme with useThemeConfig() alias.

So you think we should introduce `theme.config` and `$themeConfig` alias or keep with one unified `app.config` (with `theme` key) and `$appConfig.theme`? (I'm fine with adding alias if it makes life easier for theme authors but it adds one more file to the project and can be source of wrong placement for things like `title` that are not exactly theme specific but general app/seo config)

**Comment by Tahul** [comment]
Hello there 😄

I really love the idea of unifying these config files under core API instead of an external module.

One thing I would like to preserve though is the API we created for it via [@nuxt-themes/config](https://github.com/nuxt-themes/config).

`theme.config`, `$theme` and `useTheme` are really efficient and communicate the good concepts behind it.

Instead of enforcing a naming from the core, couldn't it be possible that we expose functions that allows to handle HMR-compatible configuration files via a module, and let modules do the rest?

These functions would allow handling and merging files in multiple layers of `extends` via minimal lines in modules and let the module authors implement the rest how they want it.

I understand the concerns on how "misplacement" of configuration keys could happen, but please understand these APIs and features has been the result of lots of iterations on how to manage these configurations, and I think we can trust documentation and examples to be a good way to advocate great patterns for future users of these APIs.

Also, official themes and starters by @nuxt-themes org (which are currently being built with `$theme` APIs...) will for sure advocate these good patterns.

**Comment by pi0** [comment]
Thanks for feedback @Tahul. Theming is a common enough feature that can benefit all ecosystem without having an extra module to be installed.

Are you suggesting to rename $themeConfig to $theme shortcut? I'm little bit afraid for this as can possibly conflict with a framework or userland plugin that injects $theme/$config for another purpose. 

As for where to put app options such as title, we are working to add SEO meta helpers as well to the core and can be reused for themes support . Placing in more generic app namespace allows reusing same config with same DX and HMR support :)  

In the end i hope we can find a solid API can benefit whole ecosystem including new themes in nuxt-themes.

**Comment by danielroe** [comment]
Stepping back from the particular question about theming and thinking more about the infrastructure Nuxt can provide to modules, what about a hybrid approach?
 - built-in support for modules 'registering' config files - these get automatically watched and merged across layers. Maybe a hook gets called that lets modules decide what to do when these get updated - of course this could be runtime config but it might also be direct module config (e.g. tailwindcss, windi, prisma, etc.). By using this hook the module would opting out of the whole nuxt lifecycle and indicating that it could handle all updates required within the hook itself. Nuxt could handle extensions, etc., even schema. API could be something like:
	  ```ts
	  interface RegisterConfigFileOptions {
	    // ... options from https://github.com/unjs/c12
	    configName
	    defaults
	    rcFile
	    dotenv
	    overrides
	  }
	  
	  function registerConfigFile(name: string, options: RegisterConfigFileOptions) {}

	  nuxt.hook('config:{name}', config => {
	    // name is the name passed to registerConfigFile
	  })
	  ```
 - built-in support for modules initiating a hmr of app config - modules can inject their own config into this and initiate an update when something happens on _module_ side, e.g. update from their own config file, or possibly a WS update or something else.
	  
	  ```ts
	  nuxt.hooks.callHook('app:config', '{namespace}', config)
	  ```

**Comment by BracketJohn** [comment]
> Same as RuntimeConfig, types can be inferred directly from config and extended from NuxtAppConfig interface from @nuxt/schema by modules and theme layers

One pattern that I would love to see applied here is strong data validation for the runtime config: In the `python` + `fastapi` ecosystem it is common to have a root `settings.py` file with runtime config definition like so ([1]):
```py
from pydantic import BaseSettings

class Settings(BaseSettings):
    app_name: str = "Awesome API"
    admin_email: str
    items_per_user: int = 50
    database_dsn: PostgresDsn
``` 

The main point about this is that `pydantic` is used to validate the data to avoid a lot of trouble for developers, devops, ... down the road:
- the `database_dsn` will be a valid, non-empty PostgreSQL DSN,
- the `items_per_user` will be a valid number
- ... and so on

For me this has been a huge boost in productivity and DX when working with fastapi: I could be sure that my configuration at least contained correctly formed data and could debug in other places when stuff was not working.

In TypeScript it would probably be possible to add similar validation via:
- `reflect-metadata` (deriving automatically from native typescript, cleanest solution but probably also requires most overhead / leads to potential compability / dep errors) ([2])
- `joi` and `yup` ([3], [4])

For me a feature like this would be a huge differentiator + I can see further use-cases like server / API data validation derived from regular typescript classes.

---

sources:
[1]: https://fastapi.tiangolo.com/advanced/settings/#create-the-settings-object
[2]: https://www.npmjs.com/package/reflect-metadata
[3]: https://www.npmjs.com/package/joi
[4]: https://www.npmjs.com/package/yup
