### ISSUE TITLE
$fetch() doesn't work with golang server?

### ISSUE THREAD

**Issue by Rusinas** [nuxt/framework#6100]
### Environment

Error while running npx nuxi info. I'm starting to think that nothing in nuxt ecosystem is working correctly.
```
PS C:\Users\andre\Desktop\Code\Tests\nuxt-fetch-bug> npx nuxi info
Nuxt CLI v3.0.0-rc.6                                                                                                     19:41:00
"yarn" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

 ERROR  Command failed: yarn --version                                                                                   19:41:01  
"yarn" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.


  "yarn" �� ���� ����७��� ��� ���譥�
  ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
```

### Reproduction

https://github.com/Rusinas/nuxt-fetch-bug

### Describe the bug

I get error `$fetch failed ()` when trying to call golang/fiber endpoint. Error message doesn't give me a clue about what is wrong. Maybe I just need some headers or something I don't know. Just check the repo.

**Comment by danielroe** [comment]
As the browser console should tell you, the issue is that your server isn't setting CORS headers.

![CleanShot 2022-07-25 at 13 46 01](https://user-images.githubusercontent.com/28706372/180780563-629b26ac-067c-402e-91ed-de46461bf991.png)

This is often something that trips people up when moving from backend -> frontend, or the reverse. See [more about CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

Here's a tldr;

```diff
  package main
  
  import (
  	"log"
  
  	"github.com/gofiber/fiber/v2"
+ 	"github.com/gofiber/fiber/v2/middleware/cors"
  )
  
  func main() {
  
  	app := fiber.New()
+ 	app.Use(cors.New())
  
  	app.Get("/", func(c *fiber.Ctx) error {
  		return c.SendStatus(fiber.StatusOK)
  	})
  
  	log.Fatal(app.Listen(":4000"))
  }
```
