### ISSUE TITLE
cannot start nuxt RC7 in workspaces

### ISSUE THREAD

**Issue by huang-julien** [nuxt/framework#6527]
### Environment

Windows and WSL

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/huang-julien/nuxt-workspace-issue

- init a nuxt app in a workspace 
- run dev

### Describe the bug

Nuxt is not starting when the root dir is in a workspace. However if i move packages/issue directory into the root dir, nuxt starts normally

### Logs

Package subpath './transform' is not defined by "exports" in /mnt/d/GIT/nuxt-workspace-issue/node_modules/unctx/package.json                                                                              17:21:29

  at new NodeError (node:internal/errors:372:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
  at resolveExports (node:internal/modules/cjs/loader:482:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (/mnt/c/Users/chakr/AppData/Roaming/npm/node_modules/nuxt/node_modules/jiti/dist/jiti.js:1:192841)
  at jiti (/mnt/c/Users/chakr/AppData/Roaming/npm/node_modules/nuxt/node_modules/jiti/dist/jiti.js:1:195025)
  at node_modules/nuxt/dist/index.mjs:17:18

 ✖ Nuxt Fatal Error      
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './transform' is not defined by "exports" in /mnt/d/GIT/nuxt-workspace-issue/node_modules/unctx/package.json

**Comment by pi0** [comment]
Hi dear @huang-julien. Thanks for providing reproduction 🙏🏼 

First looking, i had to make few changes to your monorepo structure. They are not directly related but required for a vali monorepo setup:

- `nuxt` and used dependencies (such as `uuid`) should be in each package rather than workspace
- `tsconfig.json` should be in monorepo package rather than workspace root (you can _also_ have on in root considering using full path of extends)
- Scripts (dev, build, etc) should be in each package. In monorepo root, you can use `yarn workspace <name> <command>`. I've added `app:dev` and `app:build` as example

Here is the updated repo: https://github.com/pi0/nuxt-workspace-issue (and updates: https://github.com/pi0/nuxt-workspace-issue/commit/09f5fb3b40a696180bafa6de420be206a340d0f3)

I guess could find out a related change that caused this, but as a workaround you can enable experimental `viteNode` to fix. It is also included in changes. Please let me know if that works for you.


Checking the issue on regression.

**Comment by huang-julien** [comment]
hi @pi0, thank you for this workaround ! It works ! I'll try it on a bigger repo tomorrow. Thank you again 🙏
