### ISSUE TITLE
allow disabling client-side JS entirely

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#7156]
For some use cases, users may wish to have a purely HTML + CSS website where interactivity is not required. Shipping JS to hydrate such a site is unneeded.

For these use cases, we could consider support a top level option (or a per-path route rule) to disable rendering JS preload hints + script tags within the renderer.

Some initial steps:

- [x] create module: [nuxt-zero-js](https://github.com/danielroe/nuxt-zero-js)

**Note**: We may also need to update https://github.com/nuxtlabs/vue-telescope-api to accurately detect Nuxt on such sites. At the moment, it is unaware that https://nuxt.new/ is built with Nuxt 😆

**Comment by pi0** [comment]
Pure HTML is not a normal output mode. We were considering it with @Atinux since Nuxt 2 but finally decided to not introduce but i really love this idea specially combined with reactive component islands. We can probably have a module to try this mode ahead of time. Later can be joined with route rules to set per page (or group of pages) bases.


Also good point about detection! What about a magical `<-- nuxt -->` comment replacing strings. (There is also `X-Powered-By` header but not working for static builds)

**Comment by 516310460** [comment]
This is great, just like building islands, non-interactive and interactive loading of js scripts

**Comment by harlan-zw** [comment]
It'd be great to see it in the core with some sort of support for island hydration

**Comment by 516310460** [comment]
> It'd be great to see it in the core with some sort of support for island hydration

Yes, this is the beginning of a revolution

**Comment by HelloAlexPan** [comment]
This would be the key feature for us not to switch to Astro

**Comment by miclgael** [comment]
I have written post-build hacks to do this in nuxt 2 and it is a real pain point. Kudos @danielroe

**Comment by 516310460** [comment]
> 

Support nuxt2?

**Comment by danielroe** [comment]
You can do this in Nuxt 2 by setting `render.injectScripts` to false.

**Comment by kstraszewski** [comment]
The feature looks great, it would be amazing to use it per route!

**Comment by ManasMadrecha** [comment]
Having absolutely no JS is not useful; we need some JS in header or in button to toggle dark mode.

It would be better to have this feature per component, like in Astro.
