### ISSUE TITLE
defineNuxtConfig vite server prop type error

### ISSUE THREAD

**Issue by baronkoko** [nuxt/framework#7537]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `unknown`
- Builder:          `vite`
- User Config:      `alias`, `css`, `runtimeConfig`, `build`, `modules`, `vite`, `typescript`
- Runtime Modules:  `@pinia/nuxt@0.4.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ea65tz?file=nuxt.config.ts&theme=light

### Describe the bug

A type error occurs on the `defineNuxtConfig` `vite` `server` prop
![image](https://user-images.githubusercontent.com/27996386/190343454-f88c0c49-991d-446e-9d0b-dd50745c0026.png)
In the IDE: 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/27996386/190343670-28d3bfe7-7afb-466f-8435-381dae196d81.png">
Can anyone help with this?

**Comment by danielroe** [comment]
This is intentional, as configuring this option is the source of many bugs (and unintended consequences, as this is configuration for the _vite_ dev server only, and not the Nuxt dev server, or the Nuxt build server).

If your use case is proxy, then follow https://github.com/unjs/nitro/issues/113 for easy configuration, but you can also create your own proxy within `~/server`.

**Comment by baronkoko** [comment]
@danielroe thanks, I'll look into the proxy
