### ISSUE TITLE
failed setup cannot redirect to error page if the user was already on error page

### ISSUE THREAD

**Issue by huang-julien** [nuxt/framework#7860]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cit83n?file=error.vue,pages%2Ftest.vue,app.

You'll be redirected to the error.vue, click on the reload button then a blank page should appear

### Describe the bug

Hi :smiley:  , there's is a strange bug concerning `clearError` or `createError`. 

This might be linked to https://github.com/nuxt/framework/issues/7235 ?

Navigating to /test redirect the user to an error page. I'd like to reload the page using clearError with a redirect option however the user is not being redirected to the error page and the render fails since there's a throw in Test.vue.

### Additional context

this issue might need a better title

**Comment by danielroe** [comment]
FWIW, vue-router won't redirect to the same page, and even though the error page was handling it, the route was still `/test` - so you don't need to redirect. But that's not the issue.

The issue is that on client-side, we don't show a full screen error page but instead leave it to the user to handle errors with error boundaries, hooks, etc. If you _want_ the full screen error page on client-side, then set `fatal: true` within your `createError` and you should be good to go.

**Comment by huang-julien** [comment]
I see, thank you :+1:
