### ISSUE TITLE
error page not shown after abortNavigation

### ISSUE THREAD

**Issue by vis97c** [nuxt/framework#7915]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-i5nygk?file=error.vue

### Describe the bug

When throwing an error or aborting navigation from middleware nuxt does not render the error.vue page but instead shows the default nuxt error page. If this is not the intended usage of abortNavigation please provide an alternative.

using showError on a page using middlewares would trigger the same issue.

**Comment by danielroe** [comment]
1. you need to _return_ a value from a middleware, so you return `abortNavigation`
2. middleware values are normalised to kebab case - use `middleware: 'do-nothing'` in your page
3. your error page isn't loading because of a syntax error (the variable `error` isn't defined) so it's showing the default error page as a fallback

Here's an [updated repro](https://stackblitz.com/edit/github-i5nygk-mksyve). Hope that helps.

**Comment by vis97c** [comment]
@danielroe Thanks a lot. I just wanted to point out that the documentation is not clear about requiring you to return: 

![image](https://user-images.githubusercontent.com/45251845/193302128-4212424e-c4a1-4910-a2c5-80a8e00fd0b0.png)

**Comment by danielroe** [comment]
we should fix that!
