### ISSUE TITLE
Not able to set global errorHandler

### ISSUE THREAD

**Issue by dabrowiecki** [nuxt/framework#7932]
### Environment

Nuxt project info:                                                                                                                                            16:06:09

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.15.8`
- Package Manager:  `npm@8.5.0`
- Builder:          `webpack`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `typescript`, `ssr`, `server`, `head`, `css`, `plugins`, `router`, `components`, `buildModules`, `modules`, `gtm`, `axios`, `i18n`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `8n`, `@drunomics/nuxtjs-newrelic@1.0.0-beta1`, `@nuxtjs/gtm@2.4.0`
- Build Modules:    `()`, `@nuxtjs/router@1.7.0`, `v-sanitize/nuxt`, `nuxt-basic-auth-module@1.4.1`, `nuxt-compress@5.0.0`, `@nuxt/bridge@3.0.0-27711990.d463650`
------------------------------

### Reproduction

Add a server side plugin with content from documentation page: https://v3.nuxtjs.org/getting-started/error-handling#example-with-global-error-reporting-framework
```
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.config.errorHandler = (error, context) => {
    console.log("My error handler")
  }
})
```

### Describe the bug

Expected behaviour My error handler message is displayed on error.
Example error:
```
let event2 = null
return event2.dummy
```

**Comment by danielroe** [comment]
This is not reproducible for me.

https://stackblitz.com/edit/github-rya1ep

**Comment by nford88** [comment]
Nuxi 3.0.0-rc.12
RootDir: /home/projects/github-rya1ep-up6wk9
Nuxt project info: SSR Nuxt Edge App

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `typescript`, `ssr`, `plugins`, `buildModules`, `modules`, `build`, `serverHandlers`, `devServerHandlers`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27830071.32c4527`
------------------------------

**Nuxt Bridge and SSR App** 

I can also recreate the issue of @dabrowiecki. I have a feeling it is an issue with Nuxt bridge as you do not get that error in 

Please see my slimdown live recreation  using @danielroe errorHandler plugin suggestion which does not trigger in Vue errorHandler on error.

https://stackblitz.com/edit/github-rya1ep-up6wk9?file=pages/index.vue

Force an internal error with asyncData method in index.vue (uncomment lines 48 and 49 ) check terminal. 

```
[nuxt] [request error] can't access property "dummy", test is null

[nitro] [dev] [unhandledRejection] [asyncData@file:///home/projects/github-rya1ep-up6wk9/.nuxt/dist/server/pages/index.js:46:5
promisify@file:///home/projects/github-rya1ep-up6wk9/.nuxt/dist/server/server.js:1987:15
./.nuxt/server.js/__webpack_exports__.default/asyncDatas<@file:///home/projects/github-rya1ep-up6wk9/.nuxt/dist/server/server.js:1644:82
./.nuxt/server.js/__webpack_exports__.default@file:///home/projects/github-rya1ep-up6wk9/.nuxt/dist/server/server.js:1639:51
]
```
This should return the text we stipulate in the errorHandler but it does not.



On a a side note to this issue, I do not think consola plays nicely with Nuxt/Nuxt Bridge. 

I am using consola for global logging attaching to the stdout/stderr process. It only seems to work when directly invoked consola in my examples within asyncData rather than catching all console messages. 

Also when I build and serve the SSR application, the Nitro logging defaults to verbose instead of  attaching consola. When using dev server all Nitro logging is done via consola. Strange

I can post the specific logging issue in another topic, for now I would like to try and get the Vue Error Handler resolved first.

Many thanks!

**Comment by nford88** [comment]
Can this issue be re-opened @danielroe ?

**Comment by danielroe** [comment]
This repo is for Nuxt 3. If you are having an issue with Bridge, would you open one on https://github.com/nuxt/bridge?
