### ISSUE TITLE
Class bindings are incorrect between server and client

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7959]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1wqbue-aigglg?file=pages/index.vue

### Describe the bug

When applying classes wth bindings, the conditionals aren't evaluated correctly.
For some reason, the client bindings get the server class bindings applied.

### Additional context

I'm heavily struggling to get a navigation menu going that has client-side transitions and after many hours of head-scratching I think I've isolated what seems to be a bug. Unless I'm not understanding something around process.client and process.server.

**Comment by danielroe** [comment]
The root issue here is a hydration error - your client-side class doesn't match the server rendered HTML. If you want to change the class based on client, you should default it to `server-class` and only change it to `client-class` in `onMounted` as otherwise there will be a hydration error. In the case of attrs (classes, styles, etc.) Vue doesn't throw an error but you do get strange behaviour like the kind you've reported here.

**Comment by TheDutchCoder** [comment]
Ah ok, that wasn't clear to me. Is `onMounted` only ever called client-side? Or should I still check `process.client` in there just to be safe?

**Comment by manniL** [comment]
Yes, `onMounted` is only called in client-side and never on server-side.
