### ISSUE TITLE
useHead typecheck errors

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#8343]
Hello 👋,

with the new rc12, useHead() is now fully typed but it's giving me errors for the following :

![Capture d’écran 2022-10-19 à 20 05 40](https://user-images.githubusercontent.com/85166574/196770472-9db9a9af-ea5d-4113-a2f1-589534ba2d81.png)

Small precision : the following is inside a `meta: []`
![Capture d’écran 2022-10-19 à 20 05 29](https://user-images.githubusercontent.com/85166574/196770466-42b25e69-8180-49f1-aada-d12ded95bfca.png)

References :
https://useyourloaf.com/blog/safari-15-theme-color/
https://ogp.me

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
Hey @BenjaminOddou 

Thanks for reporting this issue. Issue is fixed with [this](https://github.com/harlan-zw/zhead/commit/eed168d) and [this](https://github.com/harlan-zw/zhead/commit/a3a7dec) commits.

It's available in @vueuse/head [v1.0.0-rc.12](https://github.com/vueuse/head/releases/tag/v1.0.0-rc.12)

Should be good to close @danielroe
