### ISSUE TITLE
RC12：`--dotenv` config doesn’t work in production environment

### ISSUE THREAD

**Issue by chaselen** [nuxt/framework#8355]
### Environment

normal

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rcht8e?file=package.json

### Describe the bug

`.env.dev`

```
NUXT_PUBLIC_EXAMPLE=dev
```

`.env.prod`

```
NUXT_PUBLIC_EXAMPLE=prod
```

`nuxt.config.ts`

```typescript
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      example: '',
    },
  },
});
```

`package.json`

```json
{
  "private": true,
  "scripts": {
    "dev": "nuxt dev --dotenv .env.dev",
    "build": "nuxt build --dotenv .env.prod",
    "preview": "nuxt preview",
  }
}
```

When I run `npm run dev`，I can get `'dev'` by using `useRuntimeConfig().public.example`, but I get nothing in `npm run build && npm run preview`

**Comment by danielroe** [comment]
No, it's only for prevewing. In production you will need to read your environment variables yourself. For example, on Linux you could run `source .env && node .output/server/index.mjs`.

**Comment by chaselen** [comment]
> No, it's only for prevewing. In production you will need to read your environment variables yourself. For example, on Linux you could run `source .env && node .output/server/index.mjs`.

Is that means I should use `process.env.NUXT_PUBLIC_EXAMPLE ` instead of `useRuntimeConfig()` to get the value in production?

**Comment by danielroe** [comment]
No, you would certainly use `useRuntimeConfig()`. I mean `--dotenv` is only for previewing. In production, your `.env` file is not read and you have to manually set the variables in production.

**Comment by chaselen** [comment]
I have tried `source .env.prod && .output/server/index.mjs`, but the value of `useRuntimeConfig().public.example` is still an empty string.

**Comment by chaselen** [comment]
I found that `.env` file seems to have been loaded when I run `npm run build`, because I can get the output in `nuxt.config.ts` using `procee.env.NUXT_PUBLIC_EXAMPLE `

**Comment by danielroe** [comment]
`.env.prod` is being read when building, but it's not being used to set the default value of your runtimeConfig within the built server. Is that what you want?

I think if that's what you want, then you should define them in your nuxt.config like this:

```js
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      example: process.env.NUXT_PUBLIC_EXAMPLE || '',
    },
  },
})
```

However, I personally would likely prefer to define them at runtime rather than embed them in the build. I'm not sure we should default to injecting them in runtimeConfig at _build_, as the override behaviour is a _runtime_ behaviour

(They would of course be injected in any pages that are prerendered at build time, because that is a runtime behaviour.)

**Comment by chaselen** [comment]
Yes, I solved this problem in the same way.
