### ISSUE TITLE
Bug when accessing route without last / on production

### ISSUE THREAD

**Issue by ManuelCostanzo** [nuxt/framework#8694]
Hi! Thank you very much for this project.

I'm using Nuxt 3. When running npm run dev, all works perfect. The problem is when I host my website after npm run generate. If I enter for example to:
domain.com/users/95/ all is great, but if instead I enter to domain.com/users/95, automatically Nuxt adds domain.com/0000000010/users/95/ and of course this doesn't exists.

Someone know what is happening here? Thank you very much!

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by danielroe** [comment]
I don't think this is Nuxt; it's much more likely to be your platform. Netlify does this, for example.

**Comment by jimhlad** [comment]
@ManuelCostanzo Are you using Netlify?

If so, I recently solved this by unchecking a certain setting. I believe it's under "Post-processing" or "Asset optimization" or something similar.

**Comment by ManuelCostanzo** [comment]
Hey, thanks for your answers. I'm using AWS Amplify for deploy. Is something for pay attention?

**Comment by jimhlad** [comment]
I'm not familiar with AWS Amplify.

But I did have a similar issue where if I accessed example.com/route, it would automatically re-direct to example.com/route/. So I was getting a 301 or 302 status code instead of 200.

At first I thought it was Nuxt doing this, but in my case it was Netlify.

It sounds like your issue might be different than the one I had.

**Comment by ManuelCostanzo** [comment]
Hey, solved following this: https://lupas.medium.com/deploy-a-nuxt-spa-app-to-amazons-aws-amplify-74994d4326c1

thank you
