### ISSUE TITLE
Plugins added in modules run after components

### ISSUE THREAD

**Issue by posva** [nuxt/framework#9130]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.14.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- https://github.com/posva/bug-report-nuxt-plugin

### Describe the bug

the code within the page is run **before** the plugin, not letting the plugin add the initialization information

**Comment by danielroe** [comment]
What's happening is that the router plugin runs first and navigates to the page being requested, so that other plugins have access to the route, but have a chance to add route middleware. And then at the end `router.replace` is called so added middleware has a chance to run ...

If you want your plugin to run _before_ the router plugin you can ensure it's added after the router plugin is initialised, and therefore

```diff
- addPlugin(resolve(runtimeDir, 'plugin'))
+ nuxt.hook('modules:done', () => { addPlugin(resolve(runtimeDir, 'plugin')) })
```

Does that work for you?

**Comment by posva** [comment]
That does work. It does feel very unintuitive that adding the same code to a callback ensures the plugin is called **before**. Most of the time that would make the code execute later 😅 

Was this the case in Nuxt 2 as well? I thought plugins always executed before the initial navigation. I would personally prefer to add code if I want my plugin to happen after the initial navigation rather than the other way around because it does look more like a regular Vue app:

```ts
const app = createApp(...)
app.use(plugin)

app.mount()
// or
router.isReady().then(() => app.mount())
```

**Comment by posva** [comment]
Ah is it because the plugin gets added before
I got confused by plugin addition and execution
