### ISSUE TITLE
Ternary operator inside @click event not working

### ISSUE THREAD

**Issue by Arturexe** [nuxt/framework#9368]
### Environment

Nuxt 3 installed with:
`npm i && npm i -D @nuxtjs/tailwindcss` in a local dev environment.

### Reproduction

```
<script setup>

const state = reactive({
    auth: false
})

const showModal = (event) => {
    console.log('hello')
}
<script>

...

<button class="group font-normal" @click="false ?? showModal">
  Meet
</button>
```

The `showModal` function doesn't fire. `state.auth ? showModal : null` doesn't fire either. `@click="showModal"` works. No errors, the function is just not firing with a `ternary operator`.

### Describe the bug

Hi, I'm new to nuxt (just started with nuxt 3) and the `ternary operators` do not seem to work inside the `@click` directive.

**Comment by manniL** [comment]
`@click="false ?? showModal"` The nullish coalescing operator will only use the default value when a nullish values - `null` or `undefined` - is present.

Also, I'd highly suggest to handle this logic in the method itself or use the `disabled` property of the button instead of setting a dynamic click handler.
