### ISSUE TITLE
use(Lazy)AsyncData not caching when used in composables

### ISSUE THREAD

**Issue by tofi92** [nuxt/framework#9595]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `css`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.6.0`, `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ugv5yg-sfrist (Stable)
https://stackblitz.com/edit/github-ugv5yg-ijhnxn (rc.11)

### Describe the bug

Using `useAsyncData` (or `useLazyAsyncData`) with a fixed key in a composable fetches data for every component it is used in. Expected behaviour would be that it only fetches the data once. That was the case with rc.11 (my last rc before release), but not with rc14/release. I can't see any documentation mentioning this or any breaking change referencing this behavior.

**Comment by danielroe** [comment]
This is a deliberate change -  see https://github.com/nuxt/framework/pull/8885.

**Comment by tofi92** [comment]
Ah alright, did not see that. Thanks!

**Comment by cawa-93** [comment]
@danielroe This is very confusing. This is not mentioned anywhere in the documentation as I can see. On the contrary, it seems that requests with the same key between different pages should not be repeated but should use a shared cache. But it is not so.

Is this a bug that will be fixed in the future or is it expected behavior now? This is important, because in rc11, when performing certain mutations, I had to manually call clearNuxtData to clear related cache.

In the Stable release, there is no need to clear the cache yourself, because when switching between pages, although the cached data exists for the requested key, it is not used.

So can I delete all cache cleanup operations? Will the behavior of the load change again in the future and return to the way it was in rc11? 😵

**Comment by danielroe** [comment]
No, it was a deliberate change to remove caching behaviour by default. In future it is possible we might provide a way for users to opt-in to caching, but I am not expecting a breaking change.
