### ISSUE TITLE
flash of unstyled content with css styles inside a SFC 

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#960]
I put styles for each component inside it (SFC), and with nuxt-edge+ nuxt/bridge when refresh page it is shown without styles and after second it is applied. 
Was ok prior

**Comment by Atinux** [comment]
Is this still an issue?

**Comment by morinokami** [comment]
Hi, I have a similar problem (though I'm not using Nuxt Bridge).

When I'm using components from pages inside app.vue, they don't have styles on the first load. Here's the repository I created for reproduction:

https://github.com/morinokami/nuxt3-fouc-repro

And here's a screenshot demonstrating the problem (the word "test" at the upper left doesn't have styles on the first view, but the NuxtWelcome component does):

![Screenshot from 2021-11-28 11-10-46](https://user-images.githubusercontent.com/7889778/143726623-97effb68-d293-41ac-a88a-a1d152ca1220.png)

My environment:

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `npm@8.1.4`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

**Comment by xxSkyy** [comment]
> Hi, I have a similar problem (though I'm not using Nuxt Bridge).
> 
> When I'm using components from pages inside app.vue, they don't have styles on the first load. Here's the repository I created for reproduction:
> 
> https://github.com/morinokami/nuxt3-fouc-repro
> 
> And here's a screenshot demonstrating the problem (the word "test" at the upper left doesn't have styles on the first view, but the NuxtWelcome component does):
> 
> ![Screenshot from 2021-11-28 11-10-46](https://user-images.githubusercontent.com/7889778/143726623-97effb68-d293-41ac-a88a-a1d152ca1220.png)
> 
> My environment:
> 
>     * Operating System: `Linux`
> 
>     * Node Version:     `v16.13.0`
> 
>     * Nuxt Version:     `3.0.0-27296423.f3082ca`
> 
>     * Package Manager:  `npm@8.1.4`
> 
>     * Bundler:          `Vite`
> 
>     * User Config:      `-`
> 
>     * Runtime Modules:  `-`
> 
>     * Build Modules:    `-`

I've had this problem in nuxt3, upgraded to latest nuxt3 version and it disappeared, give it a try

**Comment by xxSkyy** [comment]
I've also noticed it while updating one of my projects from nuxt2 to nuxt-bridge.

I've investigated it a bit more and it seems like only part of css are passed from SSR, and other aren't just there. 

I've made also **[quick repro here](https://github.com/xxSkyy/example-nuxt-bridge)** and **[live demo](https://bridge-repro.skyalty.com/)**

Just refresh and see unloaded classes for split second at the center.
Also background and some class got compiled if you'll check page source

**Comment by xxSkyy** [comment]
The problem is with SSR, it doesn't include all needed styles

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/16470866/147989197-457b3db8-a957-466e-9a5c-f0de377f28f3.png">

I've checked it also on my other projects, nuxt2 ssr styles were delivered as should, nuxt bridge has huge amount of lacking styles.

**Comment by CarsonBain** [comment]
+1 for this. Upgraded a nuxt 2 project to bridge and seeing a flash of unstyled content in dev and also after using `build` and `start` to serve the production build.

Here's a quick code sandbox. On the sandbox it appears that the error only happens every few refreshes, but on my project (maybe due to more css), it's happening every refresh: https://codesandbox.io/s/nameless-http-vcxw98?file=/package.json. Can't seem to figure out how to get codesandbox to allow me to run the project in production mode, but hopefully this is enough information! Let me know if I can provide anything else.

https://www.loom.com/share/f7519268809b4e59bc2258fb8cb60f20

**Comment by n4an** [comment]
i some how resolved the problem, I not remember how, may be with
```
  // build: {
  //   optimization: {
  //     runtimeChunk: true,
  //     splitChunks: {
  //       maxSize: 240000,
  //       name: true,
  //       cacheGroups: {
  //         styles: {
  //           name: 'styles',
  //           test: /\.(css|vue)$/,
  //           chunks: 'all',
  //           enforce: true
  //         }
  //       }
  //     }
  //   }
  // },
  ```
  
I don't remember, I haven't used Nuxt since nuxt 3 beta came out (i delete all and start using next and angular), because the work done using version 2 (typescript class api + axios + i18 + auth modules) went down the drain.
